// Copyright MHGZ Project. All Rights Reserved.

#include "Animation/MHGZMotionMatchingAnimInstance.h"

#include "AbilitySystemComponent.h"
#include "AttributeSystem/MHGZAttributeSet.h"
#include "AttributeSystem/MHGZWeaponResourceComponent.h"
#include "Animation/AnimMontage.h"
#include "Animation/AnimSequenceBase.h"
#include "Animation/MHGZMotionMatchingMath.h"
#include "Animation/MHGZPoseSearchTelemetryExport.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "HAL/FileManager.h"
#include "InputSystem/MHGZWeaponInputRouterComponent.h"
#include "MHGZCharacter.h"
#include "MHGZ.h"
#include "MHGZPlayerController.h"
#include "Misc/DateTime.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "PoseSearch/MotionMatchingAnimNodeLibrary.h"
#include "PoseSearch/PoseSearchDatabase.h"
#include "PoseSearch/PoseSearchResult.h"
#include "PoseSearch/PoseSearchLibrary.h"
#include "ProfilingDebugging/TraceAuxiliary.h"
#include "WeaponRuntime/MHGZWeaponRuntimeHostComponent.h"

namespace
{
constexpr float PredictionTimes[] = { 0.0f, 0.2f, 0.5f, 0.8f, 1.0f };
constexpr float RuntimeTelemetryIntentWeight = 10.0f;
constexpr float RuntimeTelemetryDistanceToStopWeight = 4.0f;
constexpr float RuntimeTelemetryStopGaitWeight = 64.0f;
constexpr float RuntimeTelemetryMoveGaitWeight = 8.0f;
constexpr float ActionExitMoveTailSeconds = 0.08f;
constexpr float ActionExitEndEpsilonSeconds = 0.01f;

constexpr TCHAR SheathedMoveDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_Shth_Move.PSD_MH_Shth_Move");
constexpr TCHAR UnsheathedMoveDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_UnSh_Move.PSD_MH_UnSh_Move");
constexpr TCHAR SheathedActionIdleDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_Shth_ActionIdle.PSD_MH_Shth_ActionIdle");
constexpr TCHAR UnsheathedActionIdleDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_UnSh_ActionIdle.PSD_MH_UnSh_ActionIdle");
constexpr TCHAR SheathedSheatheExitDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_Shth_SheatheExit.PSD_MH_Shth_SheatheExit");
constexpr TCHAR SheathedDodgeExitDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_Shth_DodgeExit.PSD_MH_Shth_DodgeExit");
constexpr TCHAR UnsheathedDodgeExitDatabasePath[] =
	TEXT("/Game/Blueprints/Characters/Demo/Animation/MotionMatching/PSD_MH_UnSh_DodgeExit.PSD_MH_UnSh_DodgeExit");

FString BuildRuntimeTelemetryReadme()
{
	return TEXT("# MHGZ Runtime Telemetry\n\n")
		TEXT("This directory is generated by `mhgz.Telemetry.Enable 1` during PIE. Each recording has a separate session directory. ")
		TEXT("Rows within one session are correlated by `Frame`; event rows also contain `WorldTimeSeconds` and/or their source timestamp.\n\n")
		TEXT("## Directory layout\n\n")
		TEXT("```text\n")
		TEXT("<SessionId>/\n")
		TEXT("  Input/RawInput.csv              physical stick/buttons sampled at the telemetry rate\n")
		TEXT("  Input/ParsedInput.csv           every Router-resolved Input.* event\n")
		TEXT("  Character/State.csv             gameplay tags, equipment state, and GAS attributes\n")
		TEXT("  Character/Spatial.csv           position, rotation, velocity, acceleration, and movement targets\n")
		TEXT("  MotionMatching/Query.csv        runtime MM query values and state-machine modes\n")
		TEXT("  MotionMatching/Selection.csv    every selected MM candidate plus semantic comparison data\n")
		TEXT("  MotionMatching/PoseSearchCandidates.csv  optional engine-traced Top-N candidates\n")
		TEXT("  MotionMatching/PoseSearchChannelCosts.csv optional per-channel feature costs\n")
		TEXT("  MotionMatching/PoseSearchDetail.utrace    optional raw Unreal Insights trace\n")
		TEXT("  Animation/Playback.csv          active GA/actions, Montage, and Root Motion ownership\n")
		TEXT("```\n\n")
		TEXT("## Important interpretation rules\n\n")
		TEXT("- `Input/RawInput` is the physical controller state. `Input/ParsedInput` is the Router output after chord/context resolution; a missing parsed event does not prove the physical input was absent.\n")
		TEXT("- `Character/State` records current Health/MaxHealth, Stamina/MaxStamina, MoveSpeedMultiplier and owned Gameplay Tags when their AttributeSet/ASC is available. Weapon-specific resources are identified by class; add explicit fields only when that resource has a stable cross-weapon contract.\n")
		TEXT("- `MotionMatching/Selection` contains only the winning candidate. `*WeightedSquaredEstimate` is a raw diagnostic estimate using the documented schema weights; it is NOT Unreal's normalized per-channel search cost. `SearchCost` remains the engine's final total.\n")
		TEXT("- When `mhgz.Telemetry.PoseSearchDetail 1` was set before starting the session, `PoseSearchCandidates.csv` contains up to the configured Top-N of the engine-tracked candidates (the engine captures at most 256/database/search). Its total and addend costs are native trace values. `PoseSearchChannelCosts.csv` reconstructs feature-vector channel costs from the trace query and current PSS weights; do not alter PSS/schema weights before recording stops.\n")
		TEXT("- The detail mode is intentionally expensive. Keep captures short (normally 5-10 seconds) and never leave it enabled for ordinary PIE testing.\n\n")
		TEXT("## Console controls\n\n")
		TEXT("```text\n")
		TEXT("mhgz.Telemetry.Enable 1\n")
		TEXT("mhgz.Telemetry.Enable 0\n")
		TEXT("mhgz.Telemetry.SampleRateHz 60\n")
		TEXT("mhgz.Telemetry.FlushRows 60\n")
		TEXT("mhgz.Telemetry.PoseSearchDetail 1    # set before Enable 1; optional second-tier capture\n")
		TEXT("mhgz.Telemetry.PoseSearchTopN 24     # optional, range 1-256; default 24\n")
		TEXT("mhgz.MM.PostActionIdleHold 0         # default: disable post-action forced-Idle hold\n")
		TEXT("mhgz.MM.PostActionIdleHold 1         # temporary legacy comparison only\n")
		TEXT("```\n");
}

TAutoConsoleVariable<int32> CVarMHGZTelemetryEnable(
	TEXT("mhgz.Telemetry.Enable"),
	0,
	TEXT("Write categorized MHGZ runtime telemetry CSVs to Saved/RuntimeTelemetry while non-zero. "
		"Set to 0 to flush and close the current CSV."),
	ECVF_Default);

TAutoConsoleVariable<float> CVarMHGZTelemetrySampleRateHz(
	TEXT("mhgz.Telemetry.SampleRateHz"),
	60.0f,
	TEXT("Samples per second for mhgz.Telemetry.Enable. Valid range: 1 to 120."),
	ECVF_Default);

TAutoConsoleVariable<int32> CVarMHGZTelemetryFlushRows(
	TEXT("mhgz.Telemetry.FlushRows"),
	60,
	TEXT("Number of buffered runtime telemetry CSV rows written in one batch. Valid range: 1 to 600."),
	ECVF_Default);

TAutoConsoleVariable<int32> CVarMHGZTelemetryPoseSearchDetail(
	TEXT("mhgz.Telemetry.PoseSearchDetail"),
	0,
	TEXT("When non-zero before mhgz.Telemetry.Enable 1, additionally capture native Pose Search candidates and export detail CSVs on stop. ")
	TEXT("This is expensive and writes a short .utrace inside the telemetry session."),
	ECVF_Default);

TAutoConsoleVariable<int32> CVarMHGZTelemetryPoseSearchTopN(
	TEXT("mhgz.Telemetry.PoseSearchTopN"),
	24,
	TEXT("Top engine-traced Pose Search candidates exported per database/search in detail mode. Valid range: 1 to 256."),
	ECVF_Default);

TAutoConsoleVariable<int32> CVarMHGZMMPostActionIdleHold(
	TEXT("mhgz.MM.PostActionIdleHold"),
	0,
	TEXT("When non-zero, temporarily restore the post-action MM Idle hold using MMForceIdleReleaseHoldDuration. "
		"Default 0 disables only that output hold for telemetry diagnosis; the one-frame Root Motion measurement reset after release remains active."),
	ECVF_Default);

FString ToCSVString(const FString& Value)
{
	FString Escaped = Value;
	Escaped.ReplaceInline(TEXT("\""), TEXT("\"\""));
	return FString::Printf(TEXT("\"%s\""), *Escaped);
}

FString ToCSVFloat(const float Value)
{
	return FString::Printf(TEXT("%.4f"), Value);
}

FString ToCSVDouble(const double Value)
{
	return FString::Printf(TEXT("%.6f"), Value);
}

FString ToInputPhaseString(const EWeaponInputPhase Phase)
{
	if (const UEnum* Enum = StaticEnum<EWeaponInputPhase>())
	{
		return Enum->GetNameStringByValue(static_cast<int64>(Phase));
	}
	return TEXT("Unknown");
}

FString ToDirectionString(const EDirectionalInput Direction)
{
	if (const UEnum* Enum = StaticEnum<EDirectionalInput>())
	{
		return Enum->GetNameStringByValue(static_cast<int64>(Direction));
	}
	return TEXT("Unknown");
}

const UMHGZWeaponInputRouterComponent* GetInputRouter(const AMHGZCharacter* Character)
{
	const AMHGZPlayerController* Controller = Character
		? Cast<AMHGZPlayerController>(Character->GetController()) : nullptr;
	return Controller ? Controller->GetWeaponInputRouter() : nullptr;
}
}

void UMHGZMotionMatchingAnimInstance::NativeInitializeAnimation()
{
	Super::NativeInitializeAnimation();
	CachedCharacter = Cast<AMHGZCharacter>(TryGetPawnOwner());
	bHasPreviousActorLocation = false;
	bStartQueryActive = false;
	bStartQueryObservedStart = false;
	bHadMoveInput = false;
	bHasPreviousUnsheathedState = false;
	bPreviousUnsheathedState = false;
	bWasForceMMIdle = false;
	bStartInputSettling = false;
	MMForceIdleReleaseHoldRemaining = 0.0f;
	MMStartInputSettleRemaining = 0.0f;
	MMStartQueryElapsed = 0.0f;
	MMStartQueryDuration = 0.0f;
	MMActualSpeed2D = 0.0f;
	MMIntentQuery = 0.0f;
	MMDistanceToStopQuery = 0.0f;
	MMStopGaitQuery = 0.0f;
	MMMoveGaitQuery = 0.0f;
	bMMForceIdle = false;
	bMMHasLocomotionInput = false;
	bMMUnsheathedLocomotion = false;
	bMMStopRequestActive = false;
	bMMExitWantsMoveDatabase = false;
	bMMActionIdleContextActive = false;
	bMMActionIdleContextUnsheathed = false;
	MMActionIdleContextSerial = 0;
	bMMRouteSheathedActionIdle = false;
	bMMRouteUnsheathedActionIdle = false;
	NextMMActionIdleContextSerial = 1;
	MMLastNonZeroCruiseSpeed = 0.0f;
	ResetSheathedStopRequest();
	ResetLegacyStopRequest();
	ActiveSheathedGait = EMHGZStopGait::None;
	LoadActionExitDatabases();
	ResetActionExitRouting();
	ClearMMRuntimeSelections();
	DiscardMMSelectionEvents();
	DiscardMMHandoffConsumptions();
	DiscardMMActionIdleContextConsumptions();
	MMPredictedTrajectory.Samples.Reset();
}

void UMHGZMotionMatchingAnimInstance::NativeUninitializeAnimation()
{
	StopRuntimeTelemetry();
	ResetActionExitRouting();
	ClearMMRuntimeSelections();
	DiscardMMSelectionEvents();
	DiscardMMHandoffConsumptions();
	DiscardMMActionIdleContextConsumptions();
	Super::NativeUninitializeAnimation();
}

void UMHGZMotionMatchingAnimInstance::QueueMotionMatchingSelection(
	const FAnimNodeReference& AnimNodeReference,
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	EAnimNodeReferenceConversionResult ConversionResult;
	const FMotionMatchingAnimNodeReference MotionMatchingReference =
		UMotionMatchingAnimNodeLibrary::ConvertToMotionMatchingNode(AnimNodeReference,
			ConversionResult);
	if (ConversionResult != EAnimNodeReferenceConversionResult::Succeeded)
	{
		return;
	}

	FPoseSearchBlueprintResult SearchResult;
	bool bIsResultValid = false;
	UMotionMatchingAnimNodeLibrary::GetMotionMatchingSearchResult(MotionMatchingReference,
		SearchResult, bIsResultValid);
	if (!bIsResultValid || !SearchResult.SelectedAnim)
	{
		return;
	}

	FMotionMatchingSelectionEvent Event;
	Event.Frame = GFrameCounter;
	Event.Node = MotionMatchingNode;
	Event.Database = SearchResult.SelectedDatabase;
	Event.Animation = SearchResult.SelectedAnim;
	Event.AnimationTime = SearchResult.SelectedTime;
	Event.SearchCost = SearchResult.SearchCost;
	Event.WantedPlayRate = SearchResult.WantedPlayRate;
	Event.bIsContinuing = SearchResult.bIsContinuingPoseSearch;
	Event.bIsLooping = SearchResult.bLoop;
	Event.bIsMirrored = SearchResult.bIsMirrored;
	MMPendingSelectionEvents.Enqueue(MoveTemp(Event));
}

void UMHGZMotionMatchingAnimInstance::OnSheathedMotionMatchingPreUpdate(
	const FAnimUpdateContext& Context, const FAnimNodeReference& AnimNodeReference)
{
	(void)Context;
	RouteMotionMatchingPreSearch(AnimNodeReference, EMHGZMotionMatchingNode::Sheathed);
}

void UMHGZMotionMatchingAnimInstance::OnUnsheathedMotionMatchingPreUpdate(
	const FAnimUpdateContext& Context, const FAnimNodeReference& AnimNodeReference)
{
	(void)Context;
	RouteMotionMatchingPreSearch(AnimNodeReference, EMHGZMotionMatchingNode::Unsheathed);
}

void UMHGZMotionMatchingAnimInstance::OnSheathedMotionMatchingStateUpdated(
	const FAnimUpdateContext& Context, const FAnimNodeReference& AnimNodeReference)
{
	(void)Context;
	ObserveMotionMatchingPostSearch(AnimNodeReference, EMHGZMotionMatchingNode::Sheathed);
}

void UMHGZMotionMatchingAnimInstance::OnUnsheathedMotionMatchingStateUpdated(
	const FAnimUpdateContext& Context, const FAnimNodeReference& AnimNodeReference)
{
	(void)Context;
	ObserveMotionMatchingPostSearch(AnimNodeReference, EMHGZMotionMatchingNode::Unsheathed);
}

void UMHGZMotionMatchingAnimInstance::LoadActionExitDatabases()
{
	MMSheathedMoveDatabase = LoadObject<UPoseSearchDatabase>(nullptr, SheathedMoveDatabasePath);
	MMUnsheathedMoveDatabase = LoadObject<UPoseSearchDatabase>(nullptr, UnsheathedMoveDatabasePath);
	MMSheathedActionIdleDatabase = LoadObject<UPoseSearchDatabase>(nullptr,
		SheathedActionIdleDatabasePath);
	MMUnsheathedActionIdleDatabase = LoadObject<UPoseSearchDatabase>(nullptr,
		UnsheathedActionIdleDatabasePath);
	MMSheathedSheatheExitDatabase = LoadObject<UPoseSearchDatabase>(nullptr,
		SheathedSheatheExitDatabasePath);
	MMSheathedDodgeExitDatabase = LoadObject<UPoseSearchDatabase>(nullptr,
		SheathedDodgeExitDatabasePath);
	MMUnsheathedDodgeExitDatabase = LoadObject<UPoseSearchDatabase>(nullptr,
		UnsheathedDodgeExitDatabasePath);

	if (!MMSheathedMoveDatabase || !MMUnsheathedMoveDatabase
		|| !MMSheathedActionIdleDatabase || !MMUnsheathedActionIdleDatabase
		|| !MMSheathedSheatheExitDatabase || !MMSheathedDodgeExitDatabase
		|| !MMUnsheathedDodgeExitDatabase)
	{
		UE_LOG(LogMHGZ, Error,
			TEXT("[ActionExitRoute] Failed to load one or more audited Pose Search databases."));
	}
}

void UMHGZMotionMatchingAnimInstance::ResetActionExitRouting()
{
	MMSheathedActionExitRoute = EMHGZMMActionExitRoute::Move;
	MMUnsheathedActionExitRoute = EMHGZMMActionExitRoute::Move;
	MMSheathedActionExitSerial = 0;
	MMUnsheathedActionExitSerial = 0;
	MMSheathedActionExitHandoffType = EMHGZMotionMatchingHandoffType::None;
	MMUnsheathedActionExitHandoffType = EMHGZMotionMatchingHandoffType::None;
	MMSheathedActionExitSelectedTime = 0.0f;
	MMUnsheathedActionExitSelectedTime = 0.0f;
	bMMActionIdleContextActive = false;
	bMMActionIdleContextUnsheathed = false;
	MMActionIdleContextSerial = 0;
	bMMRouteSheathedActionIdle = false;
	bMMRouteUnsheathedActionIdle = false;
}

UPoseSearchDatabase* UMHGZMotionMatchingAnimInstance::GetMoveDatabase(
	const EMHGZMotionMatchingNode MotionMatchingNode) const
{
	return MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed
		? MMSheathedMoveDatabase.Get() : MMUnsheathedMoveDatabase.Get();
}

UPoseSearchDatabase* UMHGZMotionMatchingAnimInstance::GetActionIdleDatabase(
	const EMHGZMotionMatchingNode MotionMatchingNode) const
{
	return MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed
		? MMSheathedActionIdleDatabase.Get() : MMUnsheathedActionIdleDatabase.Get();
}

UPoseSearchDatabase* UMHGZMotionMatchingAnimInstance::GetExitDatabase(
	const EMHGZMotionMatchingNode MotionMatchingNode,
	const EMHGZMotionMatchingHandoffType HandoffType) const
{
	if (MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed)
	{
		switch (HandoffType)
		{
		case EMHGZMotionMatchingHandoffType::SheatheMoveExit:
			return MMSheathedSheatheExitDatabase.Get();
		case EMHGZMotionMatchingHandoffType::DodgeMoveExit:
			return MMSheathedDodgeExitDatabase.Get();
		default:
			return nullptr;
		}
	}

	return HandoffType == EMHGZMotionMatchingHandoffType::DodgeMoveExit
		? MMUnsheathedDodgeExitDatabase.Get() : nullptr;
}


float UMHGZMotionMatchingAnimInstance::GetExitDuration(
	const EMHGZMotionMatchingNode MotionMatchingNode,
	const EMHGZMotionMatchingHandoffType HandoffType) const
{
	if (MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed)
	{
		return HandoffType == EMHGZMotionMatchingHandoffType::SheatheMoveExit ? 0.3500f
			: HandoffType == EMHGZMotionMatchingHandoffType::DodgeMoveExit ? 0.2667f : 0.0f;
	}
	return HandoffType == EMHGZMotionMatchingHandoffType::DodgeMoveExit ? 0.5667f : 0.0f;
}

EMHGZMMActionExitRoute& UMHGZMotionMatchingAnimInstance::GetActionExitRoute(
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	return MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed
		? MMSheathedActionExitRoute : MMUnsheathedActionExitRoute;
}

int64& UMHGZMotionMatchingAnimInstance::GetActionExitSerial(
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	return MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed
		? MMSheathedActionExitSerial : MMUnsheathedActionExitSerial;
}

EMHGZMotionMatchingHandoffType& UMHGZMotionMatchingAnimInstance::GetActionExitHandoffType(
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	return MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed
		? MMSheathedActionExitHandoffType : MMUnsheathedActionExitHandoffType;
}

float& UMHGZMotionMatchingAnimInstance::GetActionExitSelectedTime(
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	return MotionMatchingNode == EMHGZMotionMatchingNode::Sheathed
		? MMSheathedActionExitSelectedTime : MMUnsheathedActionExitSelectedTime;
}

void UMHGZMotionMatchingAnimInstance::EnterActionIdleRoute(
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	GetActionExitRoute(MotionMatchingNode) = EMHGZMMActionExitRoute::ActionIdle;
	GetActionExitSerial(MotionMatchingNode) = 0;
	GetActionExitHandoffType(MotionMatchingNode) = EMHGZMotionMatchingHandoffType::None;
	GetActionExitSelectedTime(MotionMatchingNode) = 0.0f;
	bMMActionIdleContextActive = true;
	bMMActionIdleContextUnsheathed = MotionMatchingNode == EMHGZMotionMatchingNode::Unsheathed;
	RefreshActionIdleRouteFlags();
}

void UMHGZMotionMatchingAnimInstance::ClearActionIdleRoute(
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	GetActionExitRoute(MotionMatchingNode) = EMHGZMMActionExitRoute::Move;
	GetActionExitSerial(MotionMatchingNode) = 0;
	GetActionExitHandoffType(MotionMatchingNode) = EMHGZMotionMatchingHandoffType::None;
	GetActionExitSelectedTime(MotionMatchingNode) = 0.0f;
	if (bMMActionIdleContextActive
		&& bMMActionIdleContextUnsheathed
			== (MotionMatchingNode == EMHGZMotionMatchingNode::Unsheathed))
	{
		bMMActionIdleContextActive = false;
	}
	RefreshActionIdleRouteFlags();
}

void UMHGZMotionMatchingAnimInstance::RouteMotionMatchingPreSearch(
	const FAnimNodeReference& AnimNodeReference,
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	EAnimNodeReferenceConversionResult ConversionResult;
	const FMotionMatchingAnimNodeReference MotionMatchingReference =
		UMotionMatchingAnimNodeLibrary::ConvertToMotionMatchingNode(AnimNodeReference,
			ConversionResult);
	if (ConversionResult != EAnimNodeReferenceConversionResult::Succeeded)
	{
		return;
	}

	EMHGZMMActionExitRoute& Route = GetActionExitRoute(MotionMatchingNode);
	int64& RouteSerial = GetActionExitSerial(MotionMatchingNode);
	EMHGZMotionMatchingHandoffType& RouteHandoffType =
		GetActionExitHandoffType(MotionMatchingNode);
	float& ExitSelectedTime = GetActionExitSelectedTime(MotionMatchingNode);
	const bool bNodeMatchesCurrentStance =
		(MotionMatchingNode == EMHGZMotionMatchingNode::Unsheathed) == bMMUnsheathedLocomotion;
	const UPoseSearchDatabase* PendingExitDatabase = bNodeMatchesCurrentStance
		? GetExitDatabase(MotionMatchingNode, MMHandoffType) : nullptr;
	const bool bNewCompatibleHandoff = bMMHandoffActive && bNodeMatchesCurrentStance
		&& MMHandoffSerial > 0 && PendingExitDatabase
		&& RouteSerial != MMHandoffSerial;

	if (bNewCompatibleHandoff)
	{
		if (bMMActionIdleContextActive
			&& bMMActionIdleContextUnsheathed
				== (MotionMatchingNode == EMHGZMotionMatchingNode::Unsheathed))
		{
			bMMActionIdleContextActive = false;
			RefreshActionIdleRouteFlags();
		}
		Route = EMHGZMMActionExitRoute::AwaitExitEntry;
		RouteSerial = MMHandoffSerial;
		RouteHandoffType = MMHandoffType;
		ExitSelectedTime = 0.0f;
	}
	else if (Route == EMHGZMMActionExitRoute::Move && bMMActionIdleContextActive
		&& bMMActionIdleContextUnsheathed
			== (MotionMatchingNode == EMHGZMotionMatchingNode::Unsheathed))
	{
		EnterActionIdleRoute(MotionMatchingNode);
	}

	if (Route == EMHGZMMActionExitRoute::ActionIdle && bMMHasLocomotionInput)
	{
		ClearActionIdleRoute(MotionMatchingNode);
	}

	switch (Route)
	{
	case EMHGZMMActionExitRoute::ActionIdle:
		if (UPoseSearchDatabase* IdleDatabase = GetActionIdleDatabase(MotionMatchingNode))
		{
			UMotionMatchingAnimNodeLibrary::SetDatabaseToSearch(MotionMatchingReference, IdleDatabase,
				EPoseSearchInterruptMode::InterruptOnDatabaseChangeAndInvalidateContinuingPose);
		}
		return;

	case EMHGZMMActionExitRoute::AwaitExitEntry:
	case EMHGZMMActionExitRoute::ExitOnly:
	case EMHGZMMActionExitRoute::ExitAndMove:
		break;

	case EMHGZMMActionExitRoute::Move:
	default:
		UMotionMatchingAnimNodeLibrary::ResetDatabasesToSearch(MotionMatchingReference,
			EPoseSearchInterruptMode::DoNotInterrupt);
		return;
	}

	UPoseSearchDatabase* ExitDatabase = GetExitDatabase(MotionMatchingNode, RouteHandoffType);
	const float ExitDuration = GetExitDuration(MotionMatchingNode, RouteHandoffType);
	if (!ExitDatabase || ExitDuration <= KINDA_SMALL_NUMBER)
	{
		ClearActionIdleRoute(MotionMatchingNode);
		UMotionMatchingAnimNodeLibrary::ResetDatabasesToSearch(MotionMatchingReference,
			EPoseSearchInterruptMode::ForceInterruptAndInvalidateContinuingPose);
		return;
	}

	if (Route == EMHGZMMActionExitRoute::AwaitExitEntry)
	{
		// Fresh searches may select only the initial open window in the full Exit
		// PSD. Keeping that same database preserves its continuing pose through the
		// authored blocked body instead of creating a cross-database pose jump.
		UMotionMatchingAnimNodeLibrary::SetDatabaseToSearch(MotionMatchingReference, ExitDatabase,
			EPoseSearchInterruptMode::ForceInterruptAndInvalidateContinuingPose);
		return;
	}

	// A release that occurs during an approved MoveExit is a legal, immediate
	// Stop handoff. Its functional/root-motion phase has already ended before
	// the Handoff, so preserving the Exit continuing pose would only delay the
	// normal one-shot Stop until the authored tail. Force one ordinary Move PSD
	// search instead; its Stop query selects the normal Stop lifecycle without
	// creating an input deadzone or replaying the Exit tail.
	if (bMMExitWantsMoveDatabase)
	{
		Route = EMHGZMMActionExitRoute::ExitAndMove;
	}
	if (MHGZMotionMatching::ShouldInterruptMobileActionExitForStop(
		Route == EMHGZMMActionExitRoute::ExitAndMove, bMMStopRequestActive))
	{
		if (UPoseSearchDatabase* MoveDatabase = GetMoveDatabase(MotionMatchingNode))
		{
			ClearActionIdleRoute(MotionMatchingNode);
			UMotionMatchingAnimNodeLibrary::SetDatabaseToSearch(MotionMatchingReference,
				MoveDatabase, EPoseSearchInterruptMode::ForceInterruptAndInvalidateContinuingPose);
			return;
		}
	}

	if (Route == EMHGZMMActionExitRoute::ExitOnly
		&& ExitSelectedTime >= ExitDuration - ActionExitEndEpsilonSeconds)
	{
		EnterActionIdleRoute(MotionMatchingNode);
		if (UPoseSearchDatabase* IdleDatabase = GetActionIdleDatabase(MotionMatchingNode))
		{
			UMotionMatchingAnimNodeLibrary::SetDatabaseToSearch(MotionMatchingReference, IdleDatabase,
				EPoseSearchInterruptMode::InterruptOnDatabaseChangeAndInvalidateContinuingPose);
		}
		return;
	}

	if (Route == EMHGZMMActionExitRoute::ExitAndMove
		&& ExitSelectedTime >= ExitDuration - ActionExitEndEpsilonSeconds)
	{
		if (UPoseSearchDatabase* MoveDatabase = GetMoveDatabase(MotionMatchingNode))
		{
			// The Exit's authored tail was already available to normal MM. If its
			// continuing pose still owns the exact final sample, invalidate only that
			// stale continuation and let the regular Move PSD resolve the next pose.
			UMotionMatchingAnimNodeLibrary::SetDatabaseToSearch(MotionMatchingReference,
				MoveDatabase, EPoseSearchInterruptMode::InterruptOnDatabaseChangeAndInvalidateContinuingPose);
			return;
		}
	}

	if (Route == EMHGZMMActionExitRoute::ExitAndMove
		&& ExitSelectedTime >= ExitDuration - ActionExitMoveTailSeconds)
	{
		if (UPoseSearchDatabase* MoveDatabase = GetMoveDatabase(MotionMatchingNode))
		{
			TArray<UPoseSearchDatabase*> Databases;
			Databases.Reserve(2);
			Databases.Add(ExitDatabase);
			Databases.Add(MoveDatabase);
			UMotionMatchingAnimNodeLibrary::SetDatabasesToSearch(MotionMatchingReference, Databases,
				EPoseSearchInterruptMode::DoNotInterrupt);
			return;
		}
	}

	UMotionMatchingAnimNodeLibrary::SetDatabaseToSearch(MotionMatchingReference, ExitDatabase,
		EPoseSearchInterruptMode::DoNotInterrupt);
}

void UMHGZMotionMatchingAnimInstance::ObserveMotionMatchingPostSearch(
	const FAnimNodeReference& AnimNodeReference,
	const EMHGZMotionMatchingNode MotionMatchingNode)
{
	QueueMotionMatchingSelection(AnimNodeReference, MotionMatchingNode);

	EAnimNodeReferenceConversionResult ConversionResult;
	const FMotionMatchingAnimNodeReference MotionMatchingReference =
		UMotionMatchingAnimNodeLibrary::ConvertToMotionMatchingNode(AnimNodeReference,
			ConversionResult);
	if (ConversionResult != EAnimNodeReferenceConversionResult::Succeeded)
	{
		return;
	}

	FPoseSearchBlueprintResult SearchResult;
	bool bIsResultValid = false;
	UMotionMatchingAnimNodeLibrary::GetMotionMatchingSearchResult(MotionMatchingReference,
		SearchResult, bIsResultValid);
	if (!bIsResultValid || !SearchResult.SelectedAnim)
	{
		return;
	}

	EMHGZMMActionExitRoute& Route = GetActionExitRoute(MotionMatchingNode);
	const EMHGZMotionMatchingHandoffType RouteHandoffType =
		GetActionExitHandoffType(MotionMatchingNode);
	UPoseSearchDatabase* ExitDatabase = GetExitDatabase(MotionMatchingNode, RouteHandoffType);
	if (!ExitDatabase)
	{
		return;
	}

	if (SearchResult.SelectedDatabase == ExitDatabase)
	{
		GetActionExitSelectedTime(MotionMatchingNode) = SearchResult.SelectedTime;
		if (Route == EMHGZMMActionExitRoute::AwaitExitEntry)
		{
			Route = bMMExitWantsMoveDatabase
				? EMHGZMMActionExitRoute::ExitAndMove : EMHGZMMActionExitRoute::ExitOnly;
			QueueMotionMatchingHandoffConsumption(GetActionExitSerial(MotionMatchingNode));
		}
		return;
	}

	// The only legal way out of an ExitAndMove route is a real winning candidate
	// from the base Move PSD after the authored safe tail was opened. This keeps
	// an Exit-only route isolated until it has reached its authored end.
	if (Route == EMHGZMMActionExitRoute::ExitAndMove
		&& SearchResult.SelectedDatabase == GetMoveDatabase(MotionMatchingNode))
	{
		Route = EMHGZMMActionExitRoute::Move;
		GetActionExitSerial(MotionMatchingNode) = 0;
		GetActionExitHandoffType(MotionMatchingNode) = EMHGZMotionMatchingHandoffType::None;
		GetActionExitSelectedTime(MotionMatchingNode) = 0.0f;
	}
}
void UMHGZMotionMatchingAnimInstance::QueueMotionMatchingHandoffConsumption(
	const int64 HandoffSerial)
{
	if (HandoffSerial > 0)
	{
		MMPendingHandoffConsumptionSerials.Enqueue(HandoffSerial);
	}
}

void UMHGZMotionMatchingAnimInstance::QueueMotionMatchingActionIdleContextConsumption(
	const int64 ContextSerial)
{
	if (ContextSerial > 0)
	{
		MMPendingActionIdleContextConsumptionSerials.Enqueue(ContextSerial);
	}
}

void UMHGZMotionMatchingAnimInstance::NativeUpdateAnimation(const float DeltaSeconds)
{
	Super::NativeUpdateAnimation(DeltaSeconds);

	// Motion Matching state callbacks may run on the animation thread. Consume their
	// latest results here, on the AnimInstance update thread, before producing the
	// next query. This is deliberately independent of CSV capture.
	DrainMMSelectionEvents();

	AMHGZCharacter* Character = CachedCharacter.Get();
	if (!IsValid(Character))
	{
		Character = Cast<AMHGZCharacter>(TryGetPawnOwner());
		CachedCharacter = Character;
	}
	if (!IsValid(Character))
	{
		MMActualSpeed2D = 0.0f;
		MMIntentQuery = 0.0f;
		MMDistanceToStopQuery = 0.0f;
		MMStopGaitQuery = 0.0f;
		MMMoveGaitQuery = 0.0f;
		bMMForceIdle = false;
		bMMHasLocomotionInput = false;
		bMMUnsheathedLocomotion = false;
		bMMStopRequestActive = false;
		bMMExitWantsMoveDatabase = false;
		bMMActionIdleContextActive = false;
		bMMActionIdleContextUnsheathed = false;
		MMActionIdleContextSerial = 0;
		bMMRouteSheathedActionIdle = false;
		bMMRouteUnsheathedActionIdle = false;
		bMMHandoffActive = false;
		MMHandoffType = EMHGZMotionMatchingHandoffType::None;
		MMHandoffSerial = 0;
		MMHandoffRawMoveInput = FVector2D::ZeroVector;
		bMMHandoffHasRawMoveInput = false;
		bMMHandoffHadRawMoveInputInMobilePhase = false;
		bMMPendingStopAtHandoff = false;
		MMHandoffLastActiveRawMoveCruiseSpeed = 0.0f;
		MMLastNonZeroCruiseSpeed = 0.0f;
		MMPredictedTrajectory.Samples.Reset();
		bHasPreviousActorLocation = false;
		bStartQueryActive = false;
		bStartQueryObservedStart = false;
		bHadMoveInput = false;
		bHasPreviousUnsheathedState = false;
		bPreviousUnsheathedState = false;
		bWasForceMMIdle = false;
		bStartInputSettling = false;
		MMForceIdleReleaseHoldRemaining = 0.0f;
		MMStartInputSettleRemaining = 0.0f;
		ResetSheathedStopRequest();
		ResetLegacyStopRequest();
		ActiveSheathedGait = EMHGZStopGait::None;
		ResetActionExitRouting();
		ClearMMRuntimeSelections();
		DiscardMMHandoffConsumptions();
		DiscardMMActionIdleContextConsumptions();
		UpdateRuntimeTelemetry(nullptr, DeltaSeconds);
		return;
	}

	UpdateMotionMatchingHandoff(Character);
	// Update the public snapshot before draining acknowledgements. A graph callback
	// queues an acknowledgement after it has consumed this snapshot; consuming it on
	// the next NativeUpdate keeps the payload visible for the complete routing frame.
	DrainMMHandoffConsumptions(Character);
	DrainMMActionIdleContextConsumptions();
	bMMHasLocomotionInput = Character->bHasInput;
	bMMUnsheathedLocomotion = Character->bUnsheathed;

	const FVector CurrentLocation = Character->GetActorLocation();
	const UCharacterMovementComponent* MovementComponent = Character->GetCharacterMovement();
	const bool bMovingOnGround = MovementComponent && MovementComponent->IsMovingOnGround();
	const bool bExternalForceMMIdle = Character->bForceMMIdle;
	const float PostActionIdleHoldDuration = CVarMHGZMMPostActionIdleHold.GetValueOnGameThread() != 0
		? MMForceIdleReleaseHoldDuration
		: 0.0f;
	if (bExternalForceMMIdle)
	{
		MMForceIdleReleaseHoldRemaining = PostActionIdleHoldDuration;
	}
	else
	{
		MMForceIdleReleaseHoldRemaining = FMath::Max(0.0f,
			MMForceIdleReleaseHoldRemaining - FMath::Max(DeltaSeconds, 0.0f));
	}

	// The post-action Idle hold is a legacy comparison aid and defaults to disabled.
	// Even with it disabled, bWasForceMMIdle causes one measurement-only reset when
	// the external lock releases, so the last Montage Root Motion sample is not
	// counted as locomotion. That reset does not keep the AnimGraph in forced Idle.
	//
	// A separate two-frame input settle is graph-only. It prevents the first analogue
	// sample after the deadzone from selecting Walk Start before the stick reaches its
	// final Run/Sprint lane, but deliberately does not reset Root Motion measurement.
	if (!Character->bHasInput)
	{
		MMStartInputSettleRemaining = 0.0f;
	}
	const bool bBeginStartInputSettle = !bExternalForceMMIdle
		// The first released Root-Motion measurement frame is an action boundary,
		// not a fresh physical stick edge. Mobile Handoff recovery below decides
		// whether it remains cruise or becomes exactly one Stop.
		&& !bWasForceMMIdle
		&& !bHadMoveInput
		&& Character->bHasInput
		&& MMActualSpeed2D <= MMStartEligibilitySpeed
		&& MMStartInputSettleRemaining <= KINDA_SMALL_NUMBER
		&& MMStartInputSettleDuration > KINDA_SMALL_NUMBER;
	if (bBeginStartInputSettle)
	{
		MMStartInputSettleRemaining = MMStartInputSettleDuration;
	}
	bStartInputSettling = MMStartInputSettleRemaining > KINDA_SMALL_NUMBER;
	if (bStartInputSettling)
	{
		MMStartInputSettleRemaining = FMath::Max(0.0f,
			MMStartInputSettleRemaining - FMath::Max(DeltaSeconds, 0.0f));
	}

	const bool bMeasurementForceMMIdle = bExternalForceMMIdle
		|| MMForceIdleReleaseHoldRemaining > KINDA_SMALL_NUMBER;
	const bool bForceMMIdle = bMeasurementForceMMIdle || bStartInputSettling;
	bMMForceIdle = bForceMMIdle;
	const bool bLeavingForcedMeasurement = !bMeasurementForceMMIdle && bWasForceMMIdle;
	const bool bPreserveHandoffInput =
		MHGZMotionMatching::ShouldPreserveHandoffInputAcrossMeasurementReset(
			bLeavingForcedMeasurement, bMMHandoffActive,
			bMMHandoffHadRawMoveInputInMobilePhase, bMMHandoffHasRawMoveInput,
			bMMPendingStopAtHandoff);
	const bool bPublishActionIdleContext =
		MHGZMotionMatching::ShouldPublishActionIdleContextOnMeasurementRelease(
			bLeavingForcedMeasurement, bMMHandoffActive, Character->bHasInput);
	if (MHGZMotionMatching::ShouldResetMotionMeasurement(bMeasurementForceMMIdle,
		bWasForceMMIdle, bMovingOnGround, bHasPreviousActorLocation, DeltaSeconds))
	{
		ResetMMTemporalState(CurrentLocation, bPreserveHandoffInput);
		bMMHasLocomotionInput = Character->bHasInput;
		bMMStopRequestActive = false;
		// A release sampled by the authored mobile phase has not reached the
		// normal input-edge update yet, but it must be allowed to open the Exit
		// tail so that update can select its one legitimate Stop.
		bMMExitWantsMoveDatabase = bMMHasLocomotionInput
			|| (bPreserveHandoffInput && bMMPendingStopAtHandoff);
		if (bPublishActionIdleContext)
		{
			PublishActionIdleContext(Character->bUnsheathed);
		}
		else
		{
			RefreshActionIdleRouteFlags();
		}
		bWasForceMMIdle = bMeasurementForceMMIdle;
		UpdateRuntimeTelemetry(Character, DeltaSeconds);
		return;
	}

	const float FrameDistance = FVector::Dist2D(CurrentLocation, PreviousActorLocation);
	PreviousActorLocation = CurrentLocation;
	if (FrameDistance > MMTeleportResetDistance)
	{
		ResetMMTemporalState(CurrentLocation);
		bMMHasLocomotionInput = Character->bHasInput;
		bMMStopRequestActive = false;
		bMMExitWantsMoveDatabase = bMMHasLocomotionInput;
		bWasForceMMIdle = bMeasurementForceMMIdle;
		UpdateRuntimeTelemetry(Character, DeltaSeconds);
		return;
	}

	MMActualSpeed2D = FrameDistance / FMath::Max(DeltaSeconds, KINDA_SMALL_NUMBER);

	const bool bHasInput = Character->bHasInput;
	bMMHasLocomotionInput = bHasInput;
	const bool bUnsheathed = Character->bUnsheathed;
	const float TargetSpeed = Character->TargetCruiseSpeed;
	if (bHasPreviousUnsheathedState && bPreviousUnsheathedState != bUnsheathed)
	{
		// Do not let a result from the other locomotion database drive this path.
		ClearMMRuntimeSelections();
		ResetSheathedStopRequest();
		ResetLegacyStopRequest();
		ActiveSheathedGait = EMHGZStopGait::None;
		MMStopGaitQuery = 0.0f;
	}
	bHasPreviousUnsheathedState = true;
	bPreviousUnsheathedState = bUnsheathed;

	const bool bInputStarted = !bHadMoveInput && bHasInput
		&& MMActualSpeed2D <= MMStartEligibilitySpeed;
	const bool bInputReleased = bHadMoveInput && !bHasInput;
	MMMoveGaitQuery = bHasInput
		? GetStopGaitCurveValue(GetGaitFromTargetSpeed(TargetSpeed)) : 0.0f;
	if (bHasInput && TargetSpeed > 1.0f)
	{
		MMLastNonZeroCruiseSpeed = TargetSpeed;
	}

	if (bInputStarted)
	{
		bStartQueryActive = true;
		bStartQueryObservedStart = false;
		MMStartQueryElapsed = 0.0f;
		MMStartQueryDuration = 0.0f;
	}
	if (!bUnsheathed)
	{
		UpdateSheathedIntentQueries(bHasInput, bInputStarted, bInputReleased, DeltaSeconds,
			TargetSpeed);
	}
	else
	{
		UpdateLegacyIntentQueries(bHasInput, bInputStarted, bInputReleased, DeltaSeconds);
	}

	const float DecelerationReferenceSpeed = FMath::Max(MMActualSpeed2D,
		MMLastNonZeroCruiseSpeed);
	const float StopDeceleration = SelectStopDeceleration(bUnsheathed,
		DecelerationReferenceSpeed);
	if (bUnsheathed && LegacyStopMode == EMHGZLegacyStopMode::AwaitingStopCandidate)
	{
		MMDistanceToStopQuery = !bHasInput && MMActualSpeed2D > MMIdleSpeedThreshold
			? MHGZMotionMatching::CalculateStopDistanceQuery(MMActualSpeed2D, StopDeceleration)
			: 0.0f;
	}
	else if (bUnsheathed && LegacyStopMode != EMHGZLegacyStopMode::FollowingStopCurve)
	{
		// No player release has armed a legacy Stop. In particular, do not turn
		// residual action displacement into a generic Stop-distance query.
		MMDistanceToStopQuery = 0.0f;
	}

	const float TrajectoryTargetSpeed = bHasInput ? TargetSpeed : 0.0f;
	const float TrajectoryAcceleration = TrajectoryTargetSpeed >= MMActualSpeed2D
		? SelectStartAcceleration(bUnsheathed, TrajectoryTargetSpeed)
		: StopDeceleration;
	BuildPredictedTrajectory(Character->GetActorTransform(), MMActualSpeed2D,
		TrajectoryTargetSpeed, TrajectoryAcceleration);

	bMMStopRequestActive = SheathedStopMode != EMHGZSheathedStopMode::None
		|| LegacyStopMode != EMHGZLegacyStopMode::None;
	bMMExitWantsMoveDatabase = bMMHasLocomotionInput || bMMStopRequestActive;
	bHadMoveInput = bHasInput;
	bWasForceMMIdle = false;
	UpdateRuntimeTelemetry(Character, DeltaSeconds);
}

void UMHGZMotionMatchingAnimInstance::UpdateSheathedIntentQueries(
	const bool bHasInput, const bool bInputStarted, const bool bInputReleased,
	const float DeltaSeconds, const float TargetSpeed)
{
	if (bInputStarted)
	{
		// A new locomotion request invalidates the previous stop selection. The next
		// Motion Matching callback will publish the new Start/Loop result.
		ClearMMRuntimeSelections();
		ResetSheathedStopRequest();
	}

	if (bHasInput)
	{
		// This is intentionally derived from the actual Motion Matching result,
		// rather than the most recent analogue magnitude. A player can ease the
		// stick down from Run before releasing it; the selected Run animation is
		// still the correct gait family for its Stop.
		if (const FMotionMatchingSelectionEvent* Selection = GetLatestSelection(
			EMHGZMotionMatchingNode::Sheathed))
		{
			const EMHGZStopGait SelectionGait = GetGaitFromSelection(Selection);
			if (SelectionGait != EMHGZStopGait::None)
			{
				ActiveSheathedGait = SelectionGait;
			}
		}
		if (ActiveSheathedGait == EMHGZStopGait::None)
		{
			ActiveSheathedGait = GetGaitFromTargetSpeed(TargetSpeed);
		}

		// Re-pressing the stick before the stop animation finishes cancels the stop
		// request. It does not reuse the old stop animation as the new result.
		if (SheathedStopMode != EMHGZSheathedStopMode::None)
		{
			ResetSheathedStopRequest();
			ClearMMRuntimeSelections();
		}

		if (bStartQueryActive)
		{
			if (bStartInputSettling)
			{
				// bMMForceIdle keeps the graph on Idle during this tiny handoff.
				// Preserve the +Start semantic without advancing its timer so the
				// first real search sees the settled analogue lane at time zero.
				MMIntentQuery = 1.0f;
				MMDistanceToStopQuery = 0.0f;
				MMStopGaitQuery = 0.0f;
				return;
			}

			UpdateStartIntentQuery(EMHGZMotionMatchingNode::Sheathed, DeltaSeconds);
		}
		else
		{
			MMIntentQuery = 0.0f;
		}
		MMDistanceToStopQuery = 0.0f;
		MMStopGaitQuery = 0.0f;
		return;
	}

	if (bInputReleased)
	{
		// The falling edge is the only source of the initial stop request. It is
		// intentionally independent of measured speed and does not predict a
		// stop-distance value before a stop asset has actually been selected.
		ResetSheathedStopRequest();
		SheathedStopMode = EMHGZSheathedStopMode::AwaitingExtendedStopCandidate;
		// A mobile action-exit owns the gait at its release edge. The ordinary
		// locomotion gait can be stale (for example, Walk before a full-stick
		// MoveExit), so it is intentionally only a fallback for non-handoff stops.
		LatchedSheathedStopGait = bMMPendingStopAtHandoff
			? GetGaitFromTargetSpeed(MMHandoffLastActiveRawMoveCruiseSpeed)
			: EMHGZStopGait::None;
		if (LatchedSheathedStopGait == EMHGZStopGait::None)
		{
			LatchedSheathedStopGait = ActiveSheathedGait;
		}
		if (LatchedSheathedStopGait == EMHGZStopGait::None)
		{
			LatchedSheathedStopGait = GetGaitFromSelection(GetLatestSelection(
				EMHGZMotionMatchingNode::Sheathed));
		}
		if (LatchedSheathedStopGait == EMHGZStopGait::None)
		{
			LatchedSheathedStopGait = GetGaitFromTargetSpeed(TargetSpeed);
		}
	}
	bStartQueryActive = false;
	bStartQueryObservedStart = false;
	MMStartQueryElapsed = 0.0f;
	MMStartQueryDuration = 0.0f;

	const FMotionMatchingSelectionEvent* Selection = GetLatestSelection(
		EMHGZMotionMatchingNode::Sheathed);
	if (SheathedStopMode == EMHGZSheathedStopMode::AwaitingExtendedStopCandidate
		&& Selection && IsExtendedStopAnimation(*Selection))
	{
		BeginFollowingSheathedStop(*Selection);
	}

	if (SheathedStopMode == EMHGZSheathedStopMode::FollowingExtendedStopCurve
		&& Selection && IsExtendedStopAnimation(*Selection))
	{
		if (!IsContinuingAcceptedSheathedStop(*Selection))
		{
			// The release edge has already consumed one Stop. A non-continuing
			// re-search into a Stop entry must not restart its -1 -> 0 curve.
			ResetSheathedStopRequest();
		}
		else
		{
			const float SampledIntent = EvaluateSelectedCurve(*Selection, FName(TEXT("MM_Intent")));
			const float SampledDistance = EvaluateSelectedCurve(*Selection,
				FName(TEXT("MM_DistanceToStop")));
			MMIntentQuery = FMath::Clamp(SampledIntent, -1.0f, 0.0f);
			MMDistanceToStopQuery = FMath::Min(SampledDistance, 0.0f);
			// The release edge owns the Stop family. Never adopt the lane of a
			// candidate that happened to win one search: doing so makes a Run Stop
			// selected as Walk self-confirm on the next frame. Generated Stop assets
			// keep their indexed MM_StopGait lane constant for the same reason.
			MMStopGaitQuery = GetStopGaitCurveValue(LatchedSheathedStopGait);

			// A generated stop asset ends with both curves at zero. Clear the mode on
			// that terminal sample so the following idle/loop search is not held back.
			if (FMath::IsNearlyZero(MMIntentQuery, 0.02f)
				&& FMath::IsNearlyZero(MMDistanceToStopQuery, 0.5f))
			{
				ResetSheathedStopRequest();
				MMIntentQuery = 0.0f;
				MMDistanceToStopQuery = 0.0f;
				MMStopGaitQuery = 0.0f;
			}
			return;
		}
	}
	if (SheathedStopMode == EMHGZSheathedStopMode::FollowingExtendedStopCurve)
	{
		// The selected result has already left the stop asset. Do not leave the
		// internal mode latched if a database transition reaches Idle directly.
		ResetSheathedStopRequest();
	}

	if (SheathedStopMode == EMHGZSheathedStopMode::AwaitingExtendedStopCandidate)
	{
		MMIntentQuery = -1.0f;
		MMDistanceToStopQuery = 0.0f;
		MMStopGaitQuery = GetStopGaitCurveValue(LatchedSheathedStopGait);
	}
	else
	{
		MMIntentQuery = 0.0f;
		MMDistanceToStopQuery = 0.0f;
		MMStopGaitQuery = 0.0f;
	}
}

void UMHGZMotionMatchingAnimInstance::ResetSheathedStopRequest()
{
	SheathedStopMode = EMHGZSheathedStopMode::None;
	LatchedSheathedStopGait = EMHGZStopGait::None;
	ActiveSheathedStopAnimation.Reset();
	LastSheathedStopSelectionFrame = 0;
	LastSheathedStopAnimationTime = 0.0f;
}

void UMHGZMotionMatchingAnimInstance::BeginFollowingSheathedStop(
	const FMotionMatchingSelectionEvent& Selection)
{
	check(IsExtendedStopAnimation(Selection));
	SheathedStopMode = EMHGZSheathedStopMode::FollowingExtendedStopCurve;
	ActiveSheathedStopAnimation = Selection.Animation;
	LastSheathedStopSelectionFrame = Selection.Frame;
	LastSheathedStopAnimationTime = Selection.AnimationTime;
}

bool UMHGZMotionMatchingAnimInstance::IsContinuingAcceptedSheathedStop(
	const FMotionMatchingSelectionEvent& Selection)
{
	const bool bSameAnimation = ActiveSheathedStopAnimation.IsValid()
		&& ActiveSheathedStopAnimation == Selection.Animation;
	const bool bHasNewSelectionEvent = Selection.Frame > LastSheathedStopSelectionFrame;
	if (!MHGZMotionMatching::ShouldContinueConsumedStopSelection(bSameAnimation,
		bHasNewSelectionEvent, Selection.bIsContinuing, LastSheathedStopAnimationTime,
		Selection.AnimationTime))
	{
		return false;
	}

	if (bHasNewSelectionEvent)
	{
		LastSheathedStopSelectionFrame = Selection.Frame;
		LastSheathedStopAnimationTime = Selection.AnimationTime;
	}
	return true;
}

void UMHGZMotionMatchingAnimInstance::ResetLegacyStopRequest()
{
	LegacyStopMode = EMHGZLegacyStopMode::None;
	ActiveLegacyStopAnimation.Reset();
	LastLegacyStopSelectionFrame = 0;
	LastLegacyStopAnimationTime = 0.0f;
}

void UMHGZMotionMatchingAnimInstance::BeginFollowingLegacyStop(
	const FMotionMatchingSelectionEvent& Selection)
{
	check(IsLegacyStopAnimation(Selection));
	LegacyStopMode = EMHGZLegacyStopMode::FollowingStopCurve;
	ActiveLegacyStopAnimation = Selection.Animation;
	LastLegacyStopSelectionFrame = Selection.Frame;
	LastLegacyStopAnimationTime = Selection.AnimationTime;
}

bool UMHGZMotionMatchingAnimInstance::IsContinuingAcceptedLegacyStop(
	const FMotionMatchingSelectionEvent& Selection)
{
	const bool bSameAnimation = ActiveLegacyStopAnimation.IsValid()
		&& ActiveLegacyStopAnimation == Selection.Animation;
	const bool bHasNewSelectionEvent = Selection.Frame > LastLegacyStopSelectionFrame;
	if (!MHGZMotionMatching::ShouldContinueConsumedStopSelection(bSameAnimation,
		bHasNewSelectionEvent, Selection.bIsContinuing, LastLegacyStopAnimationTime,
		Selection.AnimationTime))
	{
		return false;
	}

	if (bHasNewSelectionEvent)
	{
		LastLegacyStopSelectionFrame = Selection.Frame;
		LastLegacyStopAnimationTime = Selection.AnimationTime;
	}
	return true;
}

void UMHGZMotionMatchingAnimInstance::UpdateLegacyIntentQueries(
	const bool bHasInput, const bool bInputStarted, const bool bInputReleased, const float DeltaSeconds)
{
	const FMotionMatchingSelectionEvent* Selection = GetLatestSelection(
		EMHGZMotionMatchingNode::Unsheathed);
	if (bHasInput)
	{
		ResetLegacyStopRequest();
	}
	else if (bInputReleased)
	{
		// A locomotion input falling edge is the only legal source of a Stop
		// request. Residual action displacement has no such edge.
		ResetLegacyStopRequest();
		LegacyStopMode = EMHGZLegacyStopMode::AwaitingStopCandidate;
	}

	if (LegacyStopMode == EMHGZLegacyStopMode::AwaitingStopCandidate
		&& Selection && IsLegacyStopAnimation(*Selection))
	{
		BeginFollowingLegacyStop(*Selection);
	}
	if (LegacyStopMode == EMHGZLegacyStopMode::FollowingStopCurve
		&& Selection && IsLegacyStopAnimation(*Selection))
	{
		if (!IsContinuingAcceptedLegacyStop(*Selection))
		{
			// A release may consume only one Stop. A fresh search into the same
			// asset cannot restart it from an earlier frame.
			ResetLegacyStopRequest();
			MMIntentQuery = 0.0f;
			MMDistanceToStopQuery = 0.0f;
		}
		else
		{
			MMIntentQuery = FMath::Clamp(EvaluateSelectedCurve(*Selection,
				FName(TEXT("MM_Intent"))), -1.0f, 0.0f);
			MMDistanceToStopQuery = FMath::Min(EvaluateSelectedCurve(*Selection,
				FName(TEXT("MM_DistanceToStop"))), 0.0f);
			if (FMath::IsNearlyZero(MMIntentQuery, 0.02f)
				&& FMath::IsNearlyZero(MMDistanceToStopQuery, 0.5f))
			{
				ResetLegacyStopRequest();
				MMIntentQuery = 0.0f;
				MMDistanceToStopQuery = 0.0f;
			}
			return;
		}
	}
	if (LegacyStopMode == EMHGZLegacyStopMode::FollowingStopCurve)
	{
		// The Stop has left the current selection before its terminal sample.
		// Do not hold a stale Stop semantic over the next global search.
		ResetLegacyStopRequest();
	}

	if (!bHasInput)
	{
		bStartQueryActive = false;
		bStartQueryObservedStart = false;
		MMStartQueryElapsed = 0.0f;
		MMStartQueryDuration = 0.0f;
	}

	if (bInputStarted)
	{
		ClearMMRuntimeSelections();
		Selection = nullptr;
		bStartQueryActive = true;
		bStartQueryObservedStart = false;
		MMStartQueryElapsed = 0.0f;
		MMStartQueryDuration = 0.0f;
	}

	if (bStartQueryActive)
	{
		UpdateStartIntentQuery(EMHGZMotionMatchingNode::Unsheathed, DeltaSeconds);
	}
	else if (LegacyStopMode == EMHGZLegacyStopMode::AwaitingStopCandidate)
	{
		MMIntentQuery = -1.0f;
	}
	else
	{
		MMIntentQuery = 0.0f;
	}
}

void UMHGZMotionMatchingAnimInstance::UpdateStartIntentQuery(
	const EMHGZMotionMatchingNode MotionMatchingNode, const float DeltaSeconds)
{
	const FMotionMatchingSelectionEvent* Selection = GetLatestSelection(MotionMatchingNode);
	if (Selection && IsStartAnimation(*Selection))
	{
		bStartQueryObservedStart = true;
		const UAnimSequenceBase* Sequence = Cast<UAnimSequenceBase>(Selection->Animation.Get());
		MMStartQueryElapsed = FMath::Max(0.0f, Selection->AnimationTime);
		MMStartQueryDuration = Sequence ? Sequence->GetPlayLength() : 0.0f;
		MMIntentQuery = FMath::Clamp(EvaluateSelectedCurve(*Selection, FName(TEXT("MM_Intent"))),
			0.0f, 1.0f);
		if (MMIntentQuery <= KINDA_SMALL_NUMBER)
		{
			bStartQueryActive = false;
		}
		return;
	}

	if (bStartQueryObservedStart)
	{
		// The selected Start has handed over to a Loop/other valid candidate. Do
		// not retain a stale positive semantic after that natural handoff.
		bStartQueryActive = false;
		MMStartQueryElapsed = 0.0f;
		MMStartQueryDuration = 0.0f;
		MMIntentQuery = 0.0f;
		return;
	}

	// Before the first Start result returns from the Motion Matching node, keep
	// the request at +1. The two-frame analogue settle occurs before this path,
	// so this cannot preserve the former deadzone Walk sample.
	MMIntentQuery = 1.0f;
	MMStartQueryElapsed += FMath::Max(DeltaSeconds, 0.0f);
}

bool UMHGZMotionMatchingAnimInstance::IsStartAnimation(
	const FMotionMatchingSelectionEvent& Selection) const
{
	const UObject* Animation = Selection.Animation.Get();
	return IsValid(Animation)
		&& Animation->GetName().Contains(TEXT("_Start"), ESearchCase::IgnoreCase);
}

bool UMHGZMotionMatchingAnimInstance::IsExtendedStopAnimation(
	const FMotionMatchingSelectionEvent& Selection) const
{
	const UObject* Animation = Selection.Animation.Get();
	if (!IsValid(Animation))
	{
		return false;
	}

	const FString AnimationName = Animation->GetName();
	return AnimationName.Contains(TEXT("FirstStepCommitStop"), ESearchCase::IgnoreCase)
		|| AnimationName.Contains(TEXT("_Stop_Left_Extended"), ESearchCase::IgnoreCase)
		|| AnimationName.Contains(TEXT("_Stop_Right_Extended"), ESearchCase::IgnoreCase);
}

bool UMHGZMotionMatchingAnimInstance::IsLegacyStopAnimation(
	const FMotionMatchingSelectionEvent& Selection) const
{
	const UObject* Animation = Selection.Animation.Get();
	return IsValid(Animation)
		&& Animation->GetName().Equals(TEXT("AS_UnSh_Walk_Stop"), ESearchCase::IgnoreCase);
}

UMHGZMotionMatchingAnimInstance::EMHGZStopGait
UMHGZMotionMatchingAnimInstance::GetGaitFromSelection(
	const FMotionMatchingSelectionEvent* Selection) const
{
	const UObject* Animation = Selection ? Selection->Animation.Get() : nullptr;
	if (!IsValid(Animation))
	{
		return EMHGZStopGait::None;
	}

	const FString AnimationName = Animation->GetName();
	if (AnimationName.Contains(TEXT("Sprint"), ESearchCase::IgnoreCase))
	{
		return EMHGZStopGait::Sprint;
	}
	if (AnimationName.Contains(TEXT("Run"), ESearchCase::IgnoreCase))
	{
		return EMHGZStopGait::Run;
	}
	if (AnimationName.Contains(TEXT("Walk"), ESearchCase::IgnoreCase))
	{
		return EMHGZStopGait::Walk;
	}
	return EMHGZStopGait::None;
}

UMHGZMotionMatchingAnimInstance::EMHGZStopGait
UMHGZMotionMatchingAnimInstance::GetGaitFromTargetSpeed(const float TargetSpeed) const
{
	if (TargetSpeed <= KINDA_SMALL_NUMBER)
	{
		return EMHGZStopGait::None;
	}

	// This is only a fail-safe for a release that occurs before the first
	// Motion Matching callback. Normal releases always use the selected
	// animation's family above, so Blueprint-tuned cruise speeds do not enter
	// this decision.
	return TargetSpeed >= 520.0f ? EMHGZStopGait::Sprint
		: (TargetSpeed >= 300.0f ? EMHGZStopGait::Run : EMHGZStopGait::Walk);
}

float UMHGZMotionMatchingAnimInstance::GetStopGaitCurveValue(const EMHGZStopGait Gait)
{
	switch (Gait)
	{
	case EMHGZStopGait::Walk:
		return 1.0f / 3.0f;
	case EMHGZStopGait::Run:
		return 2.0f / 3.0f;
	case EMHGZStopGait::Sprint:
		return 1.0f;
	default:
		return 0.0f;
	}
}

float UMHGZMotionMatchingAnimInstance::EvaluateSelectedCurve(
	const FMotionMatchingSelectionEvent& Selection, const FName CurveName) const
{
	const UAnimSequenceBase* Sequence = Cast<UAnimSequenceBase>(Selection.Animation.Get());
	if (!Sequence)
	{
		return 0.0f;
	}

	const float SampleTime = FMath::Clamp(Selection.AnimationTime, 0.0f,
		Sequence->GetPlayLength());
	return Sequence->EvaluateCurveData(CurveName,
		FAnimExtractContext(static_cast<double>(SampleTime)), true);
}

void UMHGZMotionMatchingAnimInstance::UpdateMotionMatchingHandoff(
	const AMHGZCharacter* Character)
{
	bMMHandoffActive = false;
	MMHandoffType = EMHGZMotionMatchingHandoffType::None;
	MMHandoffSerial = 0;
	MMHandoffRawMoveInput = FVector2D::ZeroVector;
	bMMHandoffHasRawMoveInput = false;
	bMMHandoffHadRawMoveInputInMobilePhase = false;
	bMMPendingStopAtHandoff = false;
	MMHandoffLastActiveRawMoveCruiseSpeed = 0.0f;

	const UMHGZWeaponRuntimeHostComponent* Host = Character
		? Character->GetWeaponRuntimeHost() : nullptr;
	FWeaponMotionMatchingHandoff Handoff;
	if (!Host || !Host->GetPendingMotionMatchingHandoff(Handoff))
	{
		return;
	}

	bMMHandoffActive = true;
	MMHandoffType = Handoff.Type;
	MMHandoffSerial = Handoff.Serial;
	MMHandoffRawMoveInput = Handoff.RawMoveInput;
	bMMHandoffHasRawMoveInput = Handoff.bHasRawMoveInputAtHandoff;
	bMMHandoffHadRawMoveInputInMobilePhase = Handoff.bHadRawMoveInputInMobilePhase;
	bMMPendingStopAtHandoff = Handoff.bPendingStopAtHandoff;
	MMHandoffLastActiveRawMoveCruiseSpeed = Handoff.LastActiveRawMoveCruiseSpeedInMobilePhase;
}

void UMHGZMotionMatchingAnimInstance::DrainMMHandoffConsumptions(
	AMHGZCharacter* Character)
{
	TSet<int64> PendingSerials;
	int64 HandoffSerial = 0;
	while (MMPendingHandoffConsumptionSerials.Dequeue(HandoffSerial))
	{
		if (HandoffSerial > 0)
		{
			PendingSerials.Add(HandoffSerial);
		}
	}

	UMHGZWeaponRuntimeHostComponent* Host = Character
		? Character->GetWeaponRuntimeHost() : nullptr;
	if (!Host)
	{
		return;
	}

	for (const int64 PendingSerial : PendingSerials)
	{
		// The Host verifies the serial, so a stale graph acknowledgement can never
		// clear a newer action's handoff payload.
		Host->ClearPendingMotionMatchingHandoff(PendingSerial);
	}
}

void UMHGZMotionMatchingAnimInstance::DiscardMMHandoffConsumptions()
{
	int64 DiscardedSerial = 0;
	while (MMPendingHandoffConsumptionSerials.Dequeue(DiscardedSerial))
	{
	}
}

void UMHGZMotionMatchingAnimInstance::PublishActionIdleContext(const bool bUnsheathed)
{
	bMMActionIdleContextActive = true;
	bMMActionIdleContextUnsheathed = bUnsheathed;
	MMActionIdleContextSerial = NextMMActionIdleContextSerial++;
	EnterActionIdleRoute(bUnsheathed ? EMHGZMotionMatchingNode::Unsheathed
		: EMHGZMotionMatchingNode::Sheathed);
	if (NextMMActionIdleContextSerial <= 0)
	{
		NextMMActionIdleContextSerial = 1;
	}
}

void UMHGZMotionMatchingAnimInstance::RefreshActionIdleRouteFlags()
{
	bMMRouteSheathedActionIdle = bMMActionIdleContextActive
		&& !bMMActionIdleContextUnsheathed;
	bMMRouteUnsheathedActionIdle = bMMActionIdleContextActive
		&& bMMActionIdleContextUnsheathed;
}

void UMHGZMotionMatchingAnimInstance::DrainMMActionIdleContextConsumptions()
{
	TSet<int64> PendingSerials;
	int64 ContextSerial = 0;
	while (MMPendingActionIdleContextConsumptionSerials.Dequeue(ContextSerial))
	{
		if (ContextSerial > 0)
		{
			PendingSerials.Add(ContextSerial);
		}
	}

	// Since E4.2 pre-search routing owns the persistent ActionIdle candidate set,
	// an old post-search Blueprint acknowledgement must never clear it. Keep this
	// queue drained for backwards compatibility with already-open editor sessions.
	(void)PendingSerials;
}

void UMHGZMotionMatchingAnimInstance::DiscardMMActionIdleContextConsumptions()
{
	int64 DiscardedSerial = 0;
	while (MMPendingActionIdleContextConsumptionSerials.Dequeue(DiscardedSerial))
	{
	}
}

void UMHGZMotionMatchingAnimInstance::UpdateRuntimeTelemetry(const AMHGZCharacter* Character,
	const float DeltaSeconds)
{
	const bool bTelemetryRequested = CVarMHGZTelemetryEnable.GetValueOnGameThread() != 0;
	if (!bTelemetryRequested)
	{
		if (bRuntimeTelemetryActive)
		{
			DrainMMSelectionEvents();
		}
		StopRuntimeTelemetry();
		DiscardMMSelectionEvents();
		bRuntimeTelemetryFailed = false;
		return;
	}

	if (!bRuntimeTelemetryActive)
	{
		if (bRuntimeTelemetryFailed || !Character || !StartRuntimeTelemetry(Character))
		{
			return;
		}
	}
	DrainMMSelectionEvents();
	const UWorld* World = Character->GetWorld();
	const float WorldTimeSeconds = World ? World->GetTimeSeconds() : 0.0f;
	CaptureParsedInputEvents(Character, WorldTimeSeconds);

	const float CaptureRateHz = FMath::Clamp(CVarMHGZTelemetrySampleRateHz.GetValueOnGameThread(),
		1.0f, 120.0f);
	const float CaptureInterval = 1.0f / CaptureRateHz;
	RuntimeTelemetryElapsed += FMath::Max(DeltaSeconds, 0.0f);
	if (RuntimeTelemetryElapsed + KINDA_SMALL_NUMBER < CaptureInterval)
	{
		return;
	}
	RuntimeTelemetryElapsed = FMath::Fmod(RuntimeTelemetryElapsed, CaptureInterval);

	const FVector Origin = Character->GetActorLocation();
	const FVector TrajectoryForward = MHGZMotionMatching::GetImportedLocomotionTrajectoryForward(
		Character->GetActorTransform());
	const bool bBlockMovement = Character->ShouldBlockMovement();
	const UMHGZWeaponRuntimeHostComponent* RuntimeHost = Character->GetWeaponRuntimeHost();
	const bool bMontageRootMotionOwned = RuntimeHost && RuntimeHost->IsMontageRootMotionOwned();
	const FVector2D RawMoveInput = Character->GetRawMoveInput();
	const float RawMoveMagnitude = RawMoveInput.Size();
	const bool bHasRawMovementInput = Character->HasRawMovementInput();
	const FVector LastRawMovementDirection = Character->GetLastMovementInputDir();
	const float ActorYaw = Character->GetActorRotation().Yaw;
	const float RawInputYaw = bHasRawMovementInput && !LastRawMovementDirection.IsNearlyZero()
		? LastRawMovementDirection.Rotation().Yaw : 0.0f;
	const float ActorToRawInputYawDelta = bHasRawMovementInput
		? FMath::FindDeltaAngleDegrees(ActorYaw, RawInputYaw) : 0.0f;
	const UCharacterMovementComponent* MovementComponent = Character->GetCharacterMovement();
	const float CharacterMovementVelocity2D = MovementComponent
		? MovementComponent->Velocity.Size2D() : 0.0f;
	const UAbilitySystemComponent* ASC = Character->GetAbilitySystemComponent();
	FGameplayTagContainer OwnedGameplayTags;
	if (ASC)
	{
		ASC->GetOwnedGameplayTags(OwnedGameplayTags);
	}
	const bool bHasAbilitySystem = ASC != nullptr;
	const float Health = ASC ? ASC->GetNumericAttribute(UMHGZAttributeSet::GetHealthAttribute()) : 0.0f;
	const float MaxHealth = ASC ? ASC->GetNumericAttribute(UMHGZAttributeSet::GetMaxHealthAttribute()) : 0.0f;
	const float Stamina = ASC ? ASC->GetNumericAttribute(UMHGZAttributeSet::GetStaminaAttribute()) : 0.0f;
	const float MaxStamina = ASC ? ASC->GetNumericAttribute(UMHGZAttributeSet::GetMaxStaminaAttribute()) : 0.0f;
	const float MoveSpeedMultiplier = ASC
		? ASC->GetNumericAttribute(UMHGZAttributeSet::GetMoveSpeedMultiplierAttribute()) : 0.0f;
	const UMHGZWeaponInputRouterComponent* InputRouter = GetInputRouter(Character);
	const FString HeldPhysicalTags = InputRouter
		? InputRouter->GetHeldPhysicalInputTagsDebugString() : FString();
	const FString ActiveActions = RuntimeHost ? RuntimeHost->GetActiveActionsDebugString() : FString();
	const FString RootMotionOwner = RuntimeHost
		? RuntimeHost->GetMontageRootMotionOwnerDebugString() : FString();
	const UMHGZWeaponResourceComponent* ResourceProvider = RuntimeHost
		? RuntimeHost->GetResourceProvider() : nullptr;
	const FString ResourceProviderClass = ResourceProvider
		? ResourceProvider->GetClass()->GetPathName() : FString();
	const UAnimMontage* ActiveMontage = GetCurrentActiveMontage();
	const float ActiveMontageTime = ActiveMontage ? Montage_GetPosition(ActiveMontage) : 0.0f;
	const float ActiveMontageLength = ActiveMontage ? ActiveMontage->GetPlayLength() : 0.0f;
	const float ActiveMontagePlayRate = ActiveMontage ? Montage_GetPlayRate(ActiveMontage) : 0.0f;

	const uint64 Frame = GFrameCounter;
	const FString FrameString = FString::Printf(TEXT("%llu"), static_cast<unsigned long long>(Frame));
	const FVector CharacterLocation = Character->GetActorLocation();
	const FRotator CharacterRotation = Character->GetActorRotation();
	const FVector CharacterVelocity = MovementComponent ? MovementComponent->Velocity : FVector::ZeroVector;
	const FVector CharacterAcceleration = MovementComponent
		? MovementComponent->GetCurrentAcceleration() : FVector::ZeroVector;

	TArray<FString> RawInputFields;
	RawInputFields.Reserve(14);
	RawInputFields.Append({ ToCSVDouble(WorldTimeSeconds), FrameString,
		ToCSVFloat(RawMoveInput.X), ToCSVFloat(RawMoveInput.Y), ToCSVFloat(RawMoveMagnitude),
		bHasRawMovementInput ? TEXT("1") : TEXT("0"), ToCSVFloat(LastRawMovementDirection.X),
		ToCSVFloat(LastRawMovementDirection.Y), ToCSVFloat(LastRawMovementDirection.Z),
		ToCSVFloat(RawInputYaw), Character->IsSprintHeld() ? TEXT("1") : TEXT("0"),
		ToCSVString(HeldPhysicalTags) });
	RuntimeTelemetryRawInputPendingRows.Add(FString::Join(RawInputFields, TEXT(",")));

	TArray<FString> StateFields;
	StateFields.Reserve(16);
	StateFields.Append({ ToCSVDouble(WorldTimeSeconds), FrameString, ToCSVString(Character->GetName()),
		bHasAbilitySystem ? TEXT("1") : TEXT("0"), Character->bUnsheathed ? TEXT("1") : TEXT("0"),
		Character->bHasInput ? TEXT("1") : TEXT("0"), bBlockMovement ? TEXT("1") : TEXT("0"),
		bMMForceIdle ? TEXT("1") : TEXT("0"), ToCSVString(OwnedGameplayTags.ToStringSimple()),
		ToCSVFloat(Health), ToCSVFloat(MaxHealth), ToCSVFloat(Stamina), ToCSVFloat(MaxStamina),
		ToCSVFloat(MoveSpeedMultiplier), ToCSVString(ResourceProviderClass) });
	RuntimeTelemetryCharacterStatePendingRows.Add(FString::Join(StateFields, TEXT(",")));

	TArray<FString> SpatialFields;
	SpatialFields.Reserve(23);
	SpatialFields.Append({ ToCSVDouble(WorldTimeSeconds), FrameString, ToCSVFloat(CharacterLocation.X),
		ToCSVFloat(CharacterLocation.Y), ToCSVFloat(CharacterLocation.Z), ToCSVFloat(CharacterRotation.Pitch),
		ToCSVFloat(CharacterRotation.Yaw), ToCSVFloat(CharacterRotation.Roll), ToCSVFloat(RawInputYaw),
		ToCSVFloat(ActorToRawInputYawDelta), ToCSVFloat(CharacterVelocity.X), ToCSVFloat(CharacterVelocity.Y),
		ToCSVFloat(CharacterVelocity.Z), ToCSVFloat(CharacterMovementVelocity2D),
		ToCSVFloat(CharacterAcceleration.X), ToCSVFloat(CharacterAcceleration.Y), ToCSVFloat(CharacterAcceleration.Z),
		ToCSVFloat(MMActualSpeed2D), ToCSVFloat(Character->TargetCruiseSpeed),
		ToCSVFloat(Character->DesiredSpeed), ToCSVFloat(Character->InputMagnitude) });
	RuntimeTelemetryCharacterSpatialPendingRows.Add(FString::Join(SpatialFields, TEXT(",")));

	TArray<FString> MMQueryFields;
	MMQueryFields.Reserve(28);
	MMQueryFields.Append({ ToCSVDouble(WorldTimeSeconds), FrameString,
		Character->bUnsheathed ? TEXT("1") : TEXT("0"), ToCSVFloat(MMIntentQuery),
		ToCSVFloat(MMDistanceToStopQuery), ToCSVFloat(MMStopGaitQuery), ToCSVFloat(MMMoveGaitQuery),
		ToCSVFloat(MMLastNonZeroCruiseSpeed), bStartQueryActive ? TEXT("1") : TEXT("0"),
		ToCSVFloat(MMStartQueryElapsed), ToCSVFloat(MMStartQueryDuration),
		FString::FromInt(static_cast<int32>(SheathedStopMode)), FString::FromInt(static_cast<int32>(LegacyStopMode)),
		Character->bForceMMIdle ? TEXT("1") : TEXT("0"), bMMForceIdle ? TEXT("1") : TEXT("0"),
		ToCSVFloat(MMForceIdleReleaseHoldRemaining), ToCSVFloat(MMStartInputSettleRemaining),
		bMMHasLocomotionInput ? TEXT("1") : TEXT("0"),
		bMMStopRequestActive ? TEXT("1") : TEXT("0"),
		bMMExitWantsMoveDatabase ? TEXT("1") : TEXT("0"),
		bMMActionIdleContextActive ? TEXT("1") : TEXT("0"),
		bMMActionIdleContextUnsheathed ? TEXT("1") : TEXT("0"),
		FString::Printf(TEXT("%lld"), MMActionIdleContextSerial),
		FString::FromInt(static_cast<int32>(MMSheathedActionExitRoute)),
		FString::FromInt(static_cast<int32>(MMUnsheathedActionExitRoute)),
		FString::Printf(TEXT("%lld"), MMSheathedActionExitSerial),
		FString::Printf(TEXT("%lld"), MMUnsheathedActionExitSerial),
		ToCSVFloat(MMSheathedActionExitSelectedTime),
		ToCSVFloat(MMUnsheathedActionExitSelectedTime),
		ToCSVFloat(GetPredictedForwardDistance(0.0f, Origin, TrajectoryForward)),
		ToCSVFloat(GetPredictedForwardDistance(0.2f, Origin, TrajectoryForward)),
		ToCSVFloat(GetPredictedForwardDistance(0.5f, Origin, TrajectoryForward)),
		ToCSVFloat(GetPredictedForwardDistance(0.8f, Origin, TrajectoryForward)),
		ToCSVFloat(GetPredictedForwardDistance(1.0f, Origin, TrajectoryForward)) });
	RuntimeTelemetryMMQueryPendingRows.Add(FString::Join(MMQueryFields, TEXT(",")));

	TArray<FString> AnimationFields;
	AnimationFields.Reserve(20);
	AnimationFields.Append({ ToCSVDouble(WorldTimeSeconds), FrameString, ToCSVString(ActiveActions),
		ToCSVString(RootMotionOwner), bMontageRootMotionOwned ? TEXT("1") : TEXT("0"),
		ToCSVString(ActiveMontage ? ActiveMontage->GetPathName() : FString()), ToCSVFloat(ActiveMontageTime),
		ToCSVFloat(ActiveMontageLength), ToCSVFloat(ActiveMontagePlayRate),
		bMMHandoffActive ? TEXT("1") : TEXT("0"),
		FString::FromInt(static_cast<int32>(MMHandoffType)),
		FString::Printf(TEXT("%lld"), MMHandoffSerial),
		ToCSVFloat(MMHandoffRawMoveInput.X), ToCSVFloat(MMHandoffRawMoveInput.Y),
		bMMHandoffHasRawMoveInput ? TEXT("1") : TEXT("0"),
		bMMHandoffHadRawMoveInputInMobilePhase ? TEXT("1") : TEXT("0"),
		bMMPendingStopAtHandoff ? TEXT("1") : TEXT("0"),
		ToCSVFloat(MMHandoffLastActiveRawMoveCruiseSpeed) });
	RuntimeTelemetryAnimationPendingRows.Add(FString::Join(AnimationFields, TEXT(",")));

	const int32 FlushRowCount = FMath::Clamp(CVarMHGZTelemetryFlushRows.GetValueOnGameThread(), 1, 600);
	if (RuntimeTelemetryRawInputPendingRows.Num() >= FlushRowCount
		|| RuntimeTelemetryParsedInputPendingRows.Num() >= FlushRowCount
		|| RuntimeTelemetryCharacterStatePendingRows.Num() >= FlushRowCount
		|| RuntimeTelemetryCharacterSpatialPendingRows.Num() >= FlushRowCount
		|| RuntimeTelemetryMMQueryPendingRows.Num() >= FlushRowCount
		|| RuntimeTelemetryMMSelectionPendingRows.Num() >= FlushRowCount
		|| RuntimeTelemetryAnimationPendingRows.Num() >= FlushRowCount)
	{
		FlushRuntimeTelemetry();
	}
}

void UMHGZMotionMatchingAnimInstance::CaptureParsedInputEvents(const AMHGZCharacter* Character,
	const float WorldTimeSeconds)
{
	const UMHGZWeaponInputRouterComponent* InputRouter = GetInputRouter(Character);
	if (!InputRouter)
	{
		return;
	}

	const TArray<FWeaponInputCaptureEvent>& Events = InputRouter->GetInputCaptureEvents();
	if (Events.IsEmpty())
	{
		return;
	}
	// Router teardown/possession restarts its monotonic serial. Start following
	// the new stream rather than permanently discarding its events.
	if (Events.Last().Serial < RuntimeTelemetryLastObservedInputEventSerial)
	{
		RuntimeTelemetryLastObservedInputEventSerial = 0;
	}
	if (RuntimeTelemetryLastObservedInputEventSerial != 0
		&& Events[0].Serial > RuntimeTelemetryLastObservedInputEventSerial + 1)
	{
		UE_LOG(LogMHGZMM, Warning,
			TEXT("[RuntimeTelemetry] Input event buffer overflowed: missing serials %llu-%llu."),
			static_cast<unsigned long long>(RuntimeTelemetryLastObservedInputEventSerial + 1),
			static_cast<unsigned long long>(Events[0].Serial - 1));
	}

	for (const FWeaponInputCaptureEvent& Event : Events)
	{
		if (Event.Serial <= RuntimeTelemetryLastObservedInputEventSerial)
		{
			continue;
		}
		RuntimeTelemetryLastObservedInputEventSerial = Event.Serial;
		const FWeaponInputSnapshot& Snapshot = Event.Snapshot;
		TArray<FString> Fields;
		Fields.Reserve(16);
		Fields.Add(ToCSVDouble(WorldTimeSeconds));
		Fields.Add(FString::Printf(TEXT("%llu"), static_cast<unsigned long long>(GFrameCounter)));
		Fields.Add(FString::Printf(TEXT("%llu"), static_cast<unsigned long long>(Event.Serial)));
		Fields.Add(ToCSVDouble(Snapshot.Timestamp));
		Fields.Add(ToCSVString(Snapshot.ResolvedInputTag.ToString()));
		Fields.Add(ToCSVString(Snapshot.SourceControlTag.ToString()));
		Fields.Add(ToCSVString(Snapshot.HeldModifierTags.ToStringSimple()));
		Fields.Add(ToCSVString(Snapshot.ContextTags.ToStringSimple()));
		Fields.Add(ToCSVString(ToInputPhaseString(Snapshot.Phase)));
		Fields.Add(FString::FromInt(static_cast<int32>(Snapshot.SequenceID)));
		Fields.Add(ToCSVFloat(Snapshot.RawMoveInput.X));
		Fields.Add(ToCSVFloat(Snapshot.RawMoveInput.Y));
		Fields.Add(ToCSVFloat(Snapshot.WorldDirection.X));
		Fields.Add(ToCSVFloat(Snapshot.WorldDirection.Y));
		Fields.Add(ToCSVFloat(Snapshot.WorldDirection.Z));
		Fields.Add(ToCSVString(ToDirectionString(Snapshot.Direction)));
		RuntimeTelemetryParsedInputPendingRows.Add(FString::Join(Fields, TEXT(",")));
	}
}

bool UMHGZMotionMatchingAnimInstance::StartRuntimeTelemetry(const AMHGZCharacter* Character)
{
	check(Character);

	const FString TelemetryRootDirectory = FPaths::Combine(FPaths::ProjectSavedDir(),
		TEXT("RuntimeTelemetry"));
	if (!IFileManager::Get().MakeDirectory(*TelemetryRootDirectory, true))
	{
		bRuntimeTelemetryFailed = true;
		UE_LOG(LogMHGZMM, Error, TEXT("[RuntimeTelemetry] Could not create root directory: %s"),
			*TelemetryRootDirectory);
		return false;
	}
	const FString ReadmePath = FPaths::Combine(TelemetryRootDirectory, TEXT("README.md"));
	if (!FFileHelper::SaveStringToFile(BuildRuntimeTelemetryReadme(), *ReadmePath,
		FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
	{
		bRuntimeTelemetryFailed = true;
		UE_LOG(LogMHGZMM, Error, TEXT("[RuntimeTelemetry] Could not write README: %s"), *ReadmePath);
		return false;
	}

	FString CharacterName = Character->GetName();
	CharacterName.ReplaceInline(TEXT("/"), TEXT("_"));
	CharacterName.ReplaceInline(TEXT("\\"), TEXT("_"));
	const FString Timestamp = FDateTime::Now().ToString(TEXT("%Y%m%d-%H%M%S"));
	const FString SessionId = FString::Printf(TEXT("%s-%s-%u"), *Timestamp, *CharacterName,
		GetUniqueID());
	RuntimeTelemetrySessionDirectory = FPaths::Combine(TelemetryRootDirectory, SessionId);
	const FString InputDirectory = FPaths::Combine(RuntimeTelemetrySessionDirectory, TEXT("Input"));
	const FString CharacterDirectory = FPaths::Combine(RuntimeTelemetrySessionDirectory, TEXT("Character"));
	const FString MotionMatchingDirectory = FPaths::Combine(RuntimeTelemetrySessionDirectory, TEXT("MotionMatching"));
	const FString AnimationDirectory = FPaths::Combine(RuntimeTelemetrySessionDirectory, TEXT("Animation"));
	for (const FString& Directory : { RuntimeTelemetrySessionDirectory, InputDirectory, CharacterDirectory,
		MotionMatchingDirectory, AnimationDirectory })
	{
		if (!IFileManager::Get().MakeDirectory(*Directory, true))
		{
			bRuntimeTelemetryFailed = true;
			UE_LOG(LogMHGZMM, Error, TEXT("[RuntimeTelemetry] Could not create session directory: %s"), *Directory);
			return false;
		}
	}

	RuntimeTelemetryRawInputFilePath = FPaths::Combine(InputDirectory, TEXT("RawInput.csv"));
	RuntimeTelemetryParsedInputFilePath = FPaths::Combine(InputDirectory, TEXT("ParsedInput.csv"));
	RuntimeTelemetryCharacterStateFilePath = FPaths::Combine(CharacterDirectory, TEXT("State.csv"));
	RuntimeTelemetryCharacterSpatialFilePath = FPaths::Combine(CharacterDirectory, TEXT("Spatial.csv"));
	RuntimeTelemetryMMQueryFilePath = FPaths::Combine(MotionMatchingDirectory, TEXT("Query.csv"));
	RuntimeTelemetryMMSelectionFilePath = FPaths::Combine(MotionMatchingDirectory, TEXT("Selection.csv"));
	RuntimeTelemetryAnimationFilePath = FPaths::Combine(AnimationDirectory, TEXT("Playback.csv"));
	RuntimeTelemetryPoseSearchTraceFilePath = FPaths::Combine(MotionMatchingDirectory,
		TEXT("PoseSearchDetail.utrace"));
	RuntimeTelemetryPoseSearchDetailDirectory = MotionMatchingDirectory;

	const FString RawInputHeader = TEXT("WorldTimeSeconds,Frame,RawMoveRight,RawMoveForward,RawMoveMagnitude,HasRawMovementInput,RawWorldDirectionX,RawWorldDirectionY,RawWorldDirectionZ,RawInputYaw,SprintHeld,HeldPhysicalInputTags") LINE_TERMINATOR;
	const FString ParsedInputHeader = TEXT("WorldTimeSeconds,Frame,EventSerial,RouterTimestamp,ResolvedInputTag,SourceControlTag,HeldModifierTags,ContextTags,Phase,SequenceID,FrozenRawMoveRight,FrozenRawMoveForward,FrozenWorldDirectionX,FrozenWorldDirectionY,FrozenWorldDirectionZ,FrozenDirection") LINE_TERMINATOR;
	const FString CharacterStateHeader = TEXT("WorldTimeSeconds,Frame,Character,HasAbilitySystem,Unsheathed,HasLocomotionInput,BlockMovement,ForceMMIdle,OwnedGameplayTags,Health,MaxHealth,Stamina,MaxStamina,MoveSpeedMultiplier,WeaponResourceClass") LINE_TERMINATOR;
	const FString CharacterSpatialHeader = TEXT("WorldTimeSeconds,Frame,LocationX,LocationY,LocationZ,ActorPitch,ActorYaw,ActorRoll,RawInputYaw,ActorToRawInputYawDelta,VelocityX,VelocityY,VelocityZ,Velocity2D,AccelerationX,AccelerationY,AccelerationZ,ActualRootMotionSpeed2D,TargetCruiseSpeed,DesiredSpeed,LocomotionInputMagnitude") LINE_TERMINATOR;
	const FString MMQueryHeader = TEXT("WorldTimeSeconds,Frame,Unsheathed,IntentQuery,DistanceToStopQuery,StopGaitQuery,MoveGaitQuery,LastNonZeroCruiseSpeed,StartQueryActive,StartQueryElapsed,StartQueryDuration,SheathedStopMode,LegacyStopMode,ExternalForceMMIdle,EffectiveForceMMIdle,ForceIdleReleaseHoldRemaining,StartInputSettleRemaining,HasLocomotionInput,StopRequestActive,ExitWantsMoveDatabase,ActionIdleContextActive,ActionIdleContextUnsheathed,ActionIdleContextSerial,SheathedActionExitRoute,UnsheathedActionExitRoute,SheathedActionExitSerial,UnsheathedActionExitSerial,SheathedExitSelectedTime,UnsheathedExitSelectedTime,PredictedDistance0,PredictedDistance0p2,PredictedDistance0p5,PredictedDistance0p8,PredictedDistance1p0") LINE_TERMINATOR;
	const FString MMSelectionHeader = TEXT("Frame,Node,SelectedDatabase,SelectedAnimation,SelectedTime,SearchCost,WantedPlayRate,HasSelectionResult,IsContinuing,IsLooping,IsMirrored,QueryIntent,QueryDistanceToStop,QueryStopGait,QueryMoveGait,CandidateIntent,CandidateDistanceToStop,CandidateStopGait,CandidateMoveGait,IntentDelta,DistanceToStopDelta,StopGaitDelta,MoveGaitDelta,IntentWeightedSquaredEstimate,DistanceToStopWeightedSquaredEstimate,StopGaitWeightedSquaredEstimate,MoveGaitWeightedSquaredEstimate") LINE_TERMINATOR;
	const FString AnimationHeader = TEXT("WorldTimeSeconds,Frame,ActiveActions,MontageRootMotionOwnerAction,MontageRootMotionOwned,ActiveMontage,ActiveMontageTime,ActiveMontageLength,ActiveMontagePlayRate,HandoffActive,HandoffType,HandoffSerial,HandoffRawMoveRight,HandoffRawMoveForward,HandoffHasRawMoveInput,HandoffHadRawMoveInputInMobilePhase,PendingStopAtHandoff,HandoffLastActiveRawMoveCruiseSpeed") LINE_TERMINATOR;
	const auto CreateCSV = [this](const FString& Header, const FString& FilePath, const TCHAR* Category) -> bool
	{
		if (FFileHelper::SaveStringToFile(Header, *FilePath,
			FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			return true;
		}
		bRuntimeTelemetryFailed = true;
		UE_LOG(LogMHGZMM, Error, TEXT("[RuntimeTelemetry] Could not create %s CSV: %s"), Category, *FilePath);
		return false;
	};
	if (!CreateCSV(RawInputHeader, RuntimeTelemetryRawInputFilePath, TEXT("raw input"))
		|| !CreateCSV(ParsedInputHeader, RuntimeTelemetryParsedInputFilePath, TEXT("parsed input"))
		|| !CreateCSV(CharacterStateHeader, RuntimeTelemetryCharacterStateFilePath, TEXT("character state"))
		|| !CreateCSV(CharacterSpatialHeader, RuntimeTelemetryCharacterSpatialFilePath, TEXT("character spatial"))
		|| !CreateCSV(MMQueryHeader, RuntimeTelemetryMMQueryFilePath, TEXT("Motion Matching query"))
		|| !CreateCSV(MMSelectionHeader, RuntimeTelemetryMMSelectionFilePath, TEXT("Motion Matching selection"))
		|| !CreateCSV(AnimationHeader, RuntimeTelemetryAnimationFilePath, TEXT("animation")))
	{
		return false;
	}

	bRuntimeTelemetryActive = true;
	bRuntimeTelemetryFailed = false;
	RuntimeTelemetryElapsed = TNumericLimits<float>::Max();
	RuntimeTelemetryRawInputPendingRows.Reset();
	RuntimeTelemetryParsedInputPendingRows.Reset();
	RuntimeTelemetryCharacterStatePendingRows.Reset();
	RuntimeTelemetryCharacterSpatialPendingRows.Reset();
	RuntimeTelemetryMMQueryPendingRows.Reset();
	RuntimeTelemetryMMSelectionPendingRows.Reset();
	RuntimeTelemetryAnimationPendingRows.Reset();
	bRuntimeTelemetryPoseSearchDetailRequested = CVarMHGZTelemetryPoseSearchDetail.GetValueOnGameThread() != 0;
	RuntimeTelemetryPoseSearchTopN = FMath::Clamp(CVarMHGZTelemetryPoseSearchTopN.GetValueOnGameThread(), 1, 256);
	bRuntimeTelemetryPoseSearchTraceActive = false;
	if (bRuntimeTelemetryPoseSearchDetailRequested)
	{
		if (FTraceAuxiliary::IsConnected())
		{
			const FString Status = TEXT("Status: Skipped\nReason: An Unreal trace was already active when this telemetry session started. ")
				TEXT("The runtime telemetry session did not take ownership of it, so no dedicated PoseSearchDetail.utrace or CSV export was produced.\n");
			FFileHelper::SaveStringToFile(Status, *FPaths::Combine(RuntimeTelemetryPoseSearchDetailDirectory,
				TEXT("PoseSearchDetail-Status.txt")), FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
			UE_LOG(LogMHGZMM, Warning, TEXT("[RuntimeTelemetry] Pose Search detail skipped because another Unreal trace is already active."));
		}
		else
		{
			FTraceAuxiliary::FOptions Options;
			Options.bTruncateFile = true;
			Options.bExcludeTail = true;
			bRuntimeTelemetryPoseSearchTraceActive = FTraceAuxiliary::Start(
				FTraceAuxiliary::EConnectionType::File, *RuntimeTelemetryPoseSearchTraceFilePath,
				TEXT("PoseSearch,Object"), &Options, LogMHGZMM);
			if (!bRuntimeTelemetryPoseSearchTraceActive)
			{
				const FString Status = TEXT("Status: Failed\nReason: Unreal Trace could not start a dedicated Pose Search file capture.\n");
				FFileHelper::SaveStringToFile(Status, *FPaths::Combine(RuntimeTelemetryPoseSearchDetailDirectory,
					TEXT("PoseSearchDetail-Status.txt")), FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
				UE_LOG(LogMHGZMM, Warning, TEXT("[RuntimeTelemetry] Pose Search detail trace did not start."));
			}
		}
	}
	DiscardMMSelectionEvents();
	RuntimeTelemetryLastObservedInputEventSerial = 0;
	if (const UMHGZWeaponInputRouterComponent* InputRouter = GetInputRouter(Character))
	{
		RuntimeTelemetryLastObservedInputEventSerial = InputRouter->GetLatestInputCaptureEventSerial();
	}
	UE_LOG(LogMHGZMM, Log, TEXT("[RuntimeTelemetry] Started: %s (PoseSearchDetail=%s, TopN=%d)"),
		*RuntimeTelemetrySessionDirectory, bRuntimeTelemetryPoseSearchTraceActive ? TEXT("On") : TEXT("Off"),
		RuntimeTelemetryPoseSearchTopN);
	return true;
}

void UMHGZMotionMatchingAnimInstance::StopRuntimeTelemetry()
{
	if (!bRuntimeTelemetryActive)
	{
		return;
	}

	FlushRuntimeTelemetry();
	const FString CompletedSessionDirectory = RuntimeTelemetrySessionDirectory;
	const FString PoseSearchTracePath = RuntimeTelemetryPoseSearchTraceFilePath;
	const FString PoseSearchDetailDirectory = RuntimeTelemetryPoseSearchDetailDirectory;
	const bool bExportPoseSearchDetail = bRuntimeTelemetryPoseSearchTraceActive;
	const int32 PoseSearchTopN = RuntimeTelemetryPoseSearchTopN;
	if (bRuntimeTelemetryPoseSearchTraceActive)
	{
		if (!FTraceAuxiliary::Stop())
		{
			UE_LOG(LogMHGZMM, Warning, TEXT("[RuntimeTelemetry] Dedicated Pose Search trace was already stopped before telemetry ended."));
		}
		bRuntimeTelemetryPoseSearchTraceActive = false;
	}
	if (bExportPoseSearchDetail)
	{
		if (!FMHGZPoseSearchTelemetryExport::ExportTraceToCSV(PoseSearchTracePath,
			PoseSearchDetailDirectory, PoseSearchTopN))
		{
			UE_LOG(LogMHGZMM, Warning, TEXT("[RuntimeTelemetry] Pose Search detail CSV export failed; the raw trace is retained at %s."),
				*PoseSearchTracePath);
		}
	}
	UE_LOG(LogMHGZMM, Log, TEXT("[RuntimeTelemetry] Stopped: %s"), *CompletedSessionDirectory);
	bRuntimeTelemetryActive = false;
	RuntimeTelemetryElapsed = 0.0f;
	RuntimeTelemetrySessionDirectory.Reset();
	RuntimeTelemetryRawInputFilePath.Reset();
	RuntimeTelemetryParsedInputFilePath.Reset();
	RuntimeTelemetryCharacterStateFilePath.Reset();
	RuntimeTelemetryCharacterSpatialFilePath.Reset();
	RuntimeTelemetryMMQueryFilePath.Reset();
	RuntimeTelemetryMMSelectionFilePath.Reset();
	RuntimeTelemetryAnimationFilePath.Reset();
	RuntimeTelemetryPoseSearchTraceFilePath.Reset();
	RuntimeTelemetryPoseSearchDetailDirectory.Reset();
	bRuntimeTelemetryPoseSearchDetailRequested = false;
	RuntimeTelemetryPoseSearchTopN = 0;
	RuntimeTelemetryLastObservedInputEventSerial = 0;
}

void UMHGZMotionMatchingAnimInstance::FlushRuntimeTelemetry()
{
	if (RuntimeTelemetryRawInputPendingRows.IsEmpty() && RuntimeTelemetryParsedInputPendingRows.IsEmpty()
		&& RuntimeTelemetryCharacterStatePendingRows.IsEmpty() && RuntimeTelemetryCharacterSpatialPendingRows.IsEmpty()
		&& RuntimeTelemetryMMQueryPendingRows.IsEmpty() && RuntimeTelemetryMMSelectionPendingRows.IsEmpty()
		&& RuntimeTelemetryAnimationPendingRows.IsEmpty())
	{
		return;
	}

	const auto AppendRows = [this](TArray<FString>& Rows, const FString& FilePath, const TCHAR* Category) -> bool
	{
		if (Rows.IsEmpty())
		{
			return true;
		}
		const FString RowsText = FString::Join(Rows, LINE_TERMINATOR) + LINE_TERMINATOR;
		if (!FFileHelper::SaveStringToFile(RowsText, *FilePath,
			FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM, &IFileManager::Get(), FILEWRITE_Append))
		{
			UE_LOG(LogMHGZMM, Error, TEXT("[RuntimeTelemetry] Could not append %s CSV: %s"),
				Category, *FilePath);
			bRuntimeTelemetryFailed = true;
			bRuntimeTelemetryActive = false;
			return false;
		}
		Rows.Reset();
		return true;
	};

	AppendRows(RuntimeTelemetryRawInputPendingRows, RuntimeTelemetryRawInputFilePath, TEXT("raw input"));
	if (bRuntimeTelemetryActive)
	{
		AppendRows(RuntimeTelemetryParsedInputPendingRows, RuntimeTelemetryParsedInputFilePath, TEXT("parsed input"));
	}
	if (bRuntimeTelemetryActive)
	{
		AppendRows(RuntimeTelemetryCharacterStatePendingRows, RuntimeTelemetryCharacterStateFilePath, TEXT("character state"));
	}
	if (bRuntimeTelemetryActive)
	{
		AppendRows(RuntimeTelemetryCharacterSpatialPendingRows, RuntimeTelemetryCharacterSpatialFilePath, TEXT("character spatial"));
	}
	if (bRuntimeTelemetryActive)
	{
		AppendRows(RuntimeTelemetryMMQueryPendingRows, RuntimeTelemetryMMQueryFilePath, TEXT("Motion Matching query"));
	}
	if (bRuntimeTelemetryActive)
	{
		AppendRows(RuntimeTelemetryMMSelectionPendingRows, RuntimeTelemetryMMSelectionFilePath, TEXT("Motion Matching selection"));
	}
	if (bRuntimeTelemetryActive)
	{
		AppendRows(RuntimeTelemetryAnimationPendingRows, RuntimeTelemetryAnimationFilePath, TEXT("animation"));
	}
}

void UMHGZMotionMatchingAnimInstance::DrainMMSelectionEvents()
{
	FMotionMatchingSelectionEvent Event;
	while (MMPendingSelectionEvents.Dequeue(Event))
	{
		const int32 NodeIndex = static_cast<int32>(Event.Node);
		if (NodeIndex >= 0 && NodeIndex < UE_ARRAY_COUNT(MMLatestSelection)
			&& (!bHasLatestSelection[NodeIndex] || Event.Frame >= MMLatestSelection[NodeIndex].Frame))
		{
			MMLatestSelection[NodeIndex] = Event;
			bHasLatestSelection[NodeIndex] = true;
		}

		if (!bRuntimeTelemetryActive)
		{
			continue;
		}

		const TCHAR* NodeName = Event.Node == EMHGZMotionMatchingNode::Sheathed
			? TEXT("Sheathed") : TEXT("Unsheathed");
		const FString DatabasePath = Event.Database.IsValid()
			? Event.Database->GetPathName() : TEXT("None");
		const FString AnimationPath = Event.Animation.IsValid()
			? Event.Animation->GetPathName() : TEXT("None");
		// These query values are the values supplied to the Motion Matching node
		// that produced this queued result. Candidate values are sampled directly
		// from the selected asset at SelectedTime. The weighted values are only
		// raw scalar diagnostics; Pose Search's normalized per-channel costs are
		// intentionally not claimed here.
		const float CandidateIntent = EvaluateSelectedCurve(Event, FName(TEXT("MM_Intent")));
		const float CandidateDistance = EvaluateSelectedCurve(Event, FName(TEXT("MM_DistanceToStop")));
		const float CandidateStopGait = EvaluateSelectedCurve(Event, FName(TEXT("MM_StopGait")));
		const float CandidateMoveGait = EvaluateSelectedCurve(Event, FName(TEXT("MM_MoveGait")));
		const float IntentDelta = CandidateIntent - MMIntentQuery;
		const float DistanceDelta = CandidateDistance - MMDistanceToStopQuery;
		const float StopGaitDelta = CandidateStopGait - MMStopGaitQuery;
		const float MoveGaitDelta = CandidateMoveGait - MMMoveGaitQuery;

		TArray<FString> Fields;
		Fields.Reserve(27);
		Fields.Append({ FString::Printf(TEXT("%llu"), static_cast<unsigned long long>(Event.Frame)),
			NodeName, ToCSVString(DatabasePath), ToCSVString(AnimationPath), ToCSVFloat(Event.AnimationTime),
			ToCSVFloat(Event.SearchCost), ToCSVFloat(Event.WantedPlayRate), TEXT("1"),
			Event.bIsContinuing ? TEXT("1") : TEXT("0"), Event.bIsLooping ? TEXT("1") : TEXT("0"),
			Event.bIsMirrored ? TEXT("1") : TEXT("0"), ToCSVFloat(MMIntentQuery),
			ToCSVFloat(MMDistanceToStopQuery), ToCSVFloat(MMStopGaitQuery), ToCSVFloat(MMMoveGaitQuery),
			ToCSVFloat(CandidateIntent), ToCSVFloat(CandidateDistance), ToCSVFloat(CandidateStopGait),
			ToCSVFloat(CandidateMoveGait), ToCSVFloat(IntentDelta), ToCSVFloat(DistanceDelta),
			ToCSVFloat(StopGaitDelta), ToCSVFloat(MoveGaitDelta),
			ToCSVFloat(RuntimeTelemetryIntentWeight * FMath::Square(IntentDelta)),
			ToCSVFloat(RuntimeTelemetryDistanceToStopWeight * FMath::Square(DistanceDelta)),
			ToCSVFloat(RuntimeTelemetryStopGaitWeight * FMath::Square(StopGaitDelta)),
			ToCSVFloat(RuntimeTelemetryMoveGaitWeight * FMath::Square(MoveGaitDelta)) });
		RuntimeTelemetryMMSelectionPendingRows.Add(FString::Join(Fields, TEXT(",")));
	}
}

void UMHGZMotionMatchingAnimInstance::DiscardMMSelectionEvents()
{
	FMotionMatchingSelectionEvent DiscardedEvent;
	while (MMPendingSelectionEvents.Dequeue(DiscardedEvent))
	{
	}
}

void UMHGZMotionMatchingAnimInstance::ClearMMRuntimeSelections()
{
	for (bool& bHasSelection : bHasLatestSelection)
	{
		bHasSelection = false;
	}
	for (FMotionMatchingSelectionEvent& Selection : MMLatestSelection)
	{
		Selection = FMotionMatchingSelectionEvent();
	}
}

const UMHGZMotionMatchingAnimInstance::FMotionMatchingSelectionEvent*
UMHGZMotionMatchingAnimInstance::GetLatestSelection(
	const EMHGZMotionMatchingNode MotionMatchingNode) const
{
	const int32 NodeIndex = static_cast<int32>(MotionMatchingNode);
	return NodeIndex >= 0 && NodeIndex < UE_ARRAY_COUNT(MMLatestSelection)
		&& bHasLatestSelection[NodeIndex]
		? &MMLatestSelection[NodeIndex]
		: nullptr;
}

float UMHGZMotionMatchingAnimInstance::GetPredictedForwardDistance(const float TimeInSeconds,
	const FVector& Origin, const FVector& TrajectoryForward) const
{
	for (const FTransformTrajectorySample& Sample : MMPredictedTrajectory.Samples)
	{
		if (FMath::IsNearlyEqual(Sample.TimeInSeconds, TimeInSeconds, KINDA_SMALL_NUMBER))
		{
			return FVector::DotProduct(Sample.Position - Origin, TrajectoryForward);
		}
	}
	return 0.0f;
}

void UMHGZMotionMatchingAnimInstance::ResetMMTemporalState(const FVector& CurrentLocation,
	const bool bPreserveMoveInput)
{
	PreviousActorLocation = CurrentLocation;
	bHasPreviousActorLocation = true;
	bStartQueryActive = false;
	bStartQueryObservedStart = false;
	bHadMoveInput = bPreserveMoveInput;
	bHasPreviousUnsheathedState = false;
	bPreviousUnsheathedState = false;
	MMStartQueryElapsed = 0.0f;
	MMStartQueryDuration = 0.0f;
	MMActualSpeed2D = 0.0f;
	MMIntentQuery = 0.0f;
	MMDistanceToStopQuery = 0.0f;
	MMStopGaitQuery = 0.0f;
	MMMoveGaitQuery = 0.0f;
	bMMStopRequestActive = false;
	bMMExitWantsMoveDatabase = false;
	MMLastNonZeroCruiseSpeed = 0.0f;
	ResetSheathedStopRequest();
	ResetLegacyStopRequest();
	ActiveSheathedGait = EMHGZStopGait::None;
	bStartInputSettling = false;
	MMStartInputSettleRemaining = 0.0f;
	ClearMMRuntimeSelections();

	if (const AMHGZCharacter* Character = CachedCharacter.Get())
	{
		BuildFlatTrajectory(Character->GetActorTransform());
	}
	else
	{
		MMPredictedTrajectory.Samples.Reset();
	}
}

void UMHGZMotionMatchingAnimInstance::BuildFlatTrajectory(const FTransform& ActorTransform)
{
	MMPredictedTrajectory.Samples.Reset(UE_ARRAY_COUNT(PredictionTimes));
	for (const float Time : PredictionTimes)
	{
		FTransformTrajectorySample& Sample = MMPredictedTrajectory.Samples.AddDefaulted_GetRef();
		Sample.TimeInSeconds = Time;
		Sample.Facing = ActorTransform.GetRotation();
		Sample.Position = ActorTransform.GetLocation();
	}
}

void UMHGZMotionMatchingAnimInstance::BuildPredictedTrajectory(const FTransform& ActorTransform,
	const float InitialSpeed, const float TargetSpeed, const float Acceleration)
{
	MMPredictedTrajectory.Samples.Reset(UE_ARRAY_COUNT(PredictionTimes));
	const FVector CurrentLocation = ActorTransform.GetLocation();
	const FVector TrajectoryForward = MHGZMotionMatching::GetImportedLocomotionTrajectoryForward(
		ActorTransform);
	for (const float Time : PredictionTimes)
	{
		FTransformTrajectorySample& Sample = MMPredictedTrajectory.Samples.AddDefaulted_GetRef();
		Sample.TimeInSeconds = Time;
		Sample.Facing = ActorTransform.GetRotation();
		Sample.Position = CurrentLocation + TrajectoryForward *
			MHGZMotionMatching::CalculatePredictedDistance(InitialSpeed, TargetSpeed,
				Acceleration, Time);
	}
}

float UMHGZMotionMatchingAnimInstance::SelectStartAcceleration(const bool bUnsheathed,
	const float TargetSpeed) const
{
	if (bUnsheathed)
	{
		return MMStartAccelerationUnsheathed;
	}

	const float WalkRunBoundary = 310.0f;
	const float RunSprintBoundary = 520.0f;
	if (TargetSpeed <= WalkRunBoundary)
	{
		return MMStartAccelerationWalk;
	}
	return TargetSpeed < RunSprintBoundary
		? MMStartAccelerationRun
		: MMStartAccelerationSprint;
}

float UMHGZMotionMatchingAnimInstance::SelectStopDeceleration(const bool bUnsheathed,
	const float ReferenceSpeed) const
{
	if (bUnsheathed)
	{
		return MMStopDecelerationRun;
	}

	if (ReferenceSpeed <= 310.0f)
	{
		return MMStopDecelerationWalk;
	}
	return ReferenceSpeed < 520.0f
		? MMStopDecelerationRun
		: MMStopDecelerationSprint;
}
